### ISSUE TITLE
clang fails to compile projects using jemalloc with error posix_memalign is missing exception specification throw

### ISSUE THREAD

**Issue by sldevel** [jemalloc/jemalloc#1557] opened 2019-07-18 08:51 UTC
Greetings,

I have been using for years jemalloc in a Second Life viewer fork, and with jemalloc v4/5 I had to disable (via #ifndef \_\_clang\_\_ in jemalloc.h) je_posix_memalign(). When I don't (or try to remove JEMALLOC_NOTHROW from the je_posix_memalign() declaration), I systematically get an error when compiling the viewer with clang:
```
In file included from linden/indra/llcommon/llmemory.h:41:
In file included from /usr/lib64/clang/8.0.1/include/xmmintrin.h:39:
/usr/lib64/clang/8.0.1/include/mm_malloc.h:39:16: error: 'posix_memalign' is missing exception specification 'throw()'
extern "C" int posix_memalign(void **__memptr, size_t __alignment, size_t __size);
               ^
linden/indra/../include/jemalloc/jemalloc.h:232:38: note: previous declaration is here
JEMALLOC_EXPORT int JEMALLOC_NOTHROW    je_posix_memalign(void **memptr,
                                        ^
linden/indra/../include/jemalloc/jemalloc.h:77:29: note: expanded from macro 'je_posix_memalign'
#  define je_posix_memalign posix_memalign
                            ^
1 error generated.

```

My build of jemalloc is generated with the following configure command:
`./configure --disable-cxx --disable-fill --disable-stats --disable-prof --disable-prof-gcc --disable-prof-libgcc --enable-xmalloc --disable-static`

I have no issue whatsoever compiling the very same code with gcc (tested with v4.6 to 8.3).

This is not a big issue for me, since my code does not use posix_memalign(), but I thought I should still report it.

**Comment by interwq** [comment] 2019-07-18 21:38
Thanks for reporting. Just realized that clang intentionally avoided the exception specifier on posix_memalign;
> // Some systems (e.g. those with GNU libc) declare posix_memalign with an
// exception specifier. Via an "egregious workaround" in
// Sema::CheckEquivalentExceptionSpec, Clang accepts the following as a valid
// redeclaration of glibc's declaration.

https://github.com/llvm-mirror/clang/blob/master/lib/Headers/mm_malloc.h#L21-L24

It looks we can workaround this in 2 ways -- 
1) Guard the NOTHROW with `#ifdef __clang__`
2) Guard the declaration of `posix_memalign` in `jemalloc.h` with `#ifndef JEMALLOC_OVERRIDE___POSIX_MEMALIGN` (from https://github.com/jemalloc/jemalloc/blob/dev/configure.ac#L1002), so that jemalloc doesn't redeclare `posix_memalign` at all.

(1) feels safer to me; I'm not sure how (2) will play with libc integration or cause header inclusion troubles. I have (1) in #1558 -- I couldn't repro the issue with my clang setup; can you please help to verify that it fixes the issue @sldevel?

**Comment by sldevel** [comment] 2019-07-18 22:49
> I have (1) in #1558 -- I couldn't repro the issue with my clang setup; can you please help to verify that it fixes the issue @sldevel?

I'm afraid #1558 changes nothing at all (exact same error for me)...

**Comment by interwq** [comment] 2019-07-18 23:03
@sldevel maybe try rerun the configure script? The header file is generated there.

**Comment by sldevel** [comment] 2019-07-19 11:32
> @sldevel maybe try rerun the configure script? The header file is generated there.

I rebuilt jemalloc from scratch, after applying your patch, as shows the error message (JEMALLOC_NOTHROW no more appearing in it, compared with the un-patched jemalloc version).
I also wrote, in my initial message: "or try to remove JEMALLOC_NOTHROW from the je_posix_memalign() declaration", so in fact I tried your solution already, by manually editing jemalloc.h.

FYI, I've been programming for the past 40 years, so I *think* I know how to apply a simple patch and compile software... :-D

**Comment by interwq** [comment] 2019-07-19 19:35
@sldevel : thanks a lot for double checking! Sorry I certainly meant no offense :)

I'm still not able to repro. One more favor to ask, could you please try define it the same way as clang, i.e. `int posix_memalign(void **__memptr, size_t __alignment, size_t __size);` and see if it compiles? If it does, add the attributes JEMALLOC_EXPORT JEMALLOC_NOTHROW JEMALLOC_CXX_THROW JEMALLOC_ATTR(nonnull(1)) one by one and see which one is the cause?

**Comment by sldevel** [comment] 2019-07-20 14:03
> I'm still not able to repro.

Perhaps because you are compiling against clang's libc and not glibc/libstdc++ ?

> One more favor to ask, could you please try .../...

Whatever I do (and I tried every combination of JEMALLOC_* macros removal), including declaring je_posix_memalign() exactly in the same way as `posix_memalign()` is declared in /usr/lib64/clang/8.0.1/include/mm_malloc.h, (`int je_posix_memalign(void **memptr, size_t alignment, size_t size);`), I get the same "_posix_memalign is missing exception specification throw()_" error from clang...

The only solutions I found to get it to compile are:
Enclose the `je_posix_memalign()` definition with `#ifndef __clang__ / #endif` in jemalloc.h (but then you can't use `posix_memalign()` in your program), or comment out the `posix_memalign()` definition in /usr/lib64/clang/8.0.1/include/mm_malloc.h...

**Comment by interwq** [comment] 2019-07-23 19:30
Many thanks for all the info @sldevel. Guarding posix_memalign probably will require to include malloc.h; not sure if will have other side effects. Will have to come back to this later.

**Comment by ericniebler** [comment] 2020-06-10 23:20
For the record, I'm seeing this too. This is the relevant code in clang that is messing with the `throw()` specifier on declarations in system headers:

https://github.com/llvm/llvm-project/blob/8f3f88d2f50d97011bf48ccc507bef033715e566/clang/lib/Sema/SemaExceptionSpec.cpp#L344-L361

```cpp
  // The new function declaration is only missing an empty exception
  // specification "throw()". If the throw() specification came from a
  // function in a system header that has C linkage, just add an empty
  // exception specification to the "new" declaration. Note that C library
  // implementations are permitted to add these nothrow exception
  // specifications.
  //
  // Likewise if the old function is a builtin.
  if (MissingEmptyExceptionSpecification && NewProto &&
      (Old->getLocation().isInvalid() ||
       Context.getSourceManager().isInSystemHeader(Old->getLocation()) ||
       Old->getBuiltinID()) &&
      Old->isExternC()) {
    New->setType(Context.getFunctionType(
        NewProto->getReturnType(), NewProto->getParamTypes(),
        NewProto->getExtProtoInfo().withExceptionSpec(EST_DynamicNone)));
    return false;
  }
```

Since this special handling is done for system headers, a workaround is to use `-isystem` instead of `-I` to specify the jemalloc include path.

**Comment by davidtgoldblatt** [comment] 2020-06-11 20:59
The Mac variant of this is fixed in the current dev branch. The linux one that @ericniebler was seeing boils down to some llvm intrinsic definition headers that disagree with the system ones. I think this is arguably a bug in the intrinsics definitions, but as a workaround making sure to include the system definitions before both the intrinsics and jemalloc.h works. I don't think we can do better than that without breaking uses that can't be worked around, so closing as either WONTFIX or NOTABUG, depending on your POV.

**Closed by davidtgoldblatt** 2020-06-11 20:59 UTC
Labels: portability

**Comment by ericniebler** [comment] 2020-06-11 22:18
Why not `#include <xmmintrin.h>` when compiling with clang (and when that header is present) from jemalloc.h _before_ you define `posix_memalign`? It's fair to say it's not a bug, but if the workaround exists, is simple, and can potentially save users like @sldevel and me a tremendous amount of hair pulling, isn't it worth it?

**Comment by davidtgoldblatt** [comment] 2020-06-11 23:55
Well so, there are two different issues here -- @sldevel's is the more straightforward "most usages break on OS X in reasonable scenarios", which is definitely worth doing something about.

The xmmintrin.h thing is much more esoteric (that's the use case we're abandoning). Once we pollute the namespace in that way it's going to be difficult to undo it without potentially breaking user code.

**Comment by ericniebler** [comment] 2020-06-12 18:47
I'm afraid I don't see the problem you're talking about. Including a system header is polluting the namespace? In what way?

**Comment by davidtgoldblatt** [comment] 2020-06-12 19:14
Like, just `#include <jemalloc/jemalloc.h>` should not start letting AVX intrinsics compile.
