### ISSUE TITLE
tsd.h assertion

### ISSUE THREAD

**Issue by yuslepukhin** [jemalloc/jemalloc#441] opened 2016-08-02 23:24 UTC
Intermittently, while running different executables with jemalloc 4.2.1 I am seeing this:

WARNING: db_sst_test_je.exe : <jemalloc>: c:\dev\oss\pool.jemalloc\include\jemalloc\internal\tsd.h:674: Failed assertion: "tsd->state == tsd_state_reincarnated" 

What could this mean?

**Comment by yuslepukhin** [comment] 2016-08-16 23:28
Here is more info:

ucrtbase!abort(void) in d:\th\minkernel\crts\ucrt\src\appcrt\startup\abort.cpp@77
test_jemalloc!je_tsd_fetch(void) in c:\dev\oss\pool.jemalloc\include\jemalloc\internal\tsd.h@674
test_jemalloc!chunk_merge_default(void * chunk_a = 0x0000007c`28970240, unsigned int64 size_a = 0x0000007c`28970240, void * chunk_b = 0x0000007c`28970240, unsigned int64 size_b = 0x00007ff9`43f54552, bool committed = false, unsigned int arena_ind = 0) in c:\dev\oss\pool.jemalloc\src\chunk.c@740
test_jemalloc!chunk_record(struct tsdn_s * tsdn = 0x00000000`00000000, struct arena_s * arena = 0x0000007c`28970240, struct chunk_hooks_t * chunk_hooks = 0x0000007c`9d8ef860, struct extent_tree_t * chunks_szad = 0x0000007c`28970a78, struct extent_tree_t * chunks_ad = 0x0000007c`28970a80, bool cache = true, void * chunk = 0x0000007c`642a0000, unsigned int64 size = 0x10000, bool zeroed = false, bool committed = true) in c:\dev\oss\pool.jemalloc\src\chunk.c@526
test_jemalloc!je_chunk_dalloc_cache(struct tsdn_s * tsdn = 0x00000000`00000000, struct arena_s * arena = 0x0000007c`28970240, struct chunk_hooks_t * chunk_hooks = <Value unavailable error>, void * chunk = <Value unavailable error>, unsigned int64 size = 0x10000, bool committed = true) in c:\dev\oss\pool.jemalloc\src\chunk.c@609
test_jemalloc!arena_chunk_discard(struct tsdn_s * tsdn = 0x00000000`00000000, struct arena_s * arena = 0x0000007c`28970240, struct arena_chunk_s * chunk = 0x0000007c`642a0000) in c:\dev\oss\pool.jemalloc\src\arena.c@774
test_jemalloc!arena_chunk_dalloc(struct tsdn_s * tsdn = 0x00000000`00000000, struct arena_s * arena = 0x0000007c`28970240, struct arena_chunk_s * chunk = 0x0000007c`61600000) in c:\dev\oss\pool.jemalloc\src\arena.c@817
test_jemalloc!arena_run_dalloc(struct tsdn_s * tsdn = 0x00000000`00000000, struct arena_s * arena = 0x0000007c`28970240, struct arena_run_s * run = <Value unavailable error>, bool dirty = <Value unavailable error>, bool cleaned = false, bool decommitted = false) in c:\dev\oss\pool.jemalloc\src\arena.c@2161
test_jemalloc!arena_dalloc_bin_run(struct tsdn_s * tsdn = 0x00000000`00000000, struct arena_s * arena = 0x0000007c`28970240, struct arena_chunk_s * chunk = 0x0000007c`61600000, struct arena_run_s * run = 0x0000007c`61600570, struct arena_bin_s * bin = 0x0000007c`28970f78) in c:\dev\oss\pool.jemalloc\src\arena.c@2856
test_jemalloc!arena_dalloc_bin_locked_impl(struct tsdn_s * tsdn = 0x00000000`00000000, struct arena_s * arena = 0x0000007c`28970240, struct arena_chunk_s * chunk = 0x0000007c`61600000, void * ptr = 0x0000007c`6160c280, struct arena_chunk_map_bits_s * bitselm = 0x0000007c`616000c0, bool junked = false) in c:\dev\oss\pool.jemalloc\src\arena.c@2907
test_jemalloc!je_arena_dalloc_bin(struct tsdn_s * tsdn = 0x00000000`00000000, struct arena_s * arena = 0x0000007c`28970240, struct arena_chunk_s * chunk = 0x0000007c`61600000, void * ptr = 0x0000007c`6160c280, unsigned int64 pageind = 0xc, struct arena_chunk_map_bits_s * bitselm = 0x0000007c`616000c0) in c:\dev\oss\pool.jemalloc\src\arena.c@2938
test_jemalloc!je_arena_dalloc_small(struct tsdn_s * tsdn = 0x00000000`00000000, struct arena_s * arena = 0x0000007c`28970240, struct arena_chunk_s * chunk = 0x0000007c`61600000, void * ptr = 0x0000007c`6160c280, unsigned int64 pageind = 0xc) in c:\dev\oss\pool.jemalloc\src\arena.c@2954
test_jemalloc!je_arena_dalloc(struct tsdn_s * tsdn = 0x00000000`00000000, void * ptr = 0x0000007c`6160c280, struct tcache_s * tcache = 0x00000000`00000000, bool slow_path = true) in c:\dev\oss\pool.jemalloc\include\jemalloc\internal\arena.h@1435
test_jemalloc!je_malloc_tsd_dalloc() in c:\dev\oss\pool.jemalloc\src\tsd.c@25
test_jemalloc!je_tsd_cleanup_wrapper(void) in c:\dev\oss\pool.jemalloc\include\jemalloc\internal\tsd.h@658
test_jemalloc!_malloc_thread_cleanup(void) in c:\dev\oss\pool.jemalloc\src\tsd.c@53
test_jemalloc!_tls_callback(struct HINSTANCE__ * hinstDLL = 0x00000000`00000007, unsigned long fdwReason = 0xf, void * lpvReserved = 0x00007ff9`5636f610) in c:\dev\oss\pool.jemalloc\src\tsd.c@146

**Comment by yuslepukhin** [comment] 2016-08-17 00:10
![tsdassertion](https://cloud.githubusercontent.com/assets/11303988/17720113/47f9e2c0-63d4-11e6-94b9-7a9976cc7db5.PNG)

**Comment by yuslepukhin** [comment] 2016-08-18 18:32
This bug does not reproduce on 4.2.0. There is only a handful of commits between 4.2.0 and 4.2.1. Working on a simple repro case. Suspect this is related to tsd changes.

Jemalloc is built with --with-debug on.

The basic scenario is that a number of threads is created and they do their job and start exiting while other threads are either still running or still starting up.

This goes on until one of the exiting threads does tsd clean up and discovers that the memory under TSD strucure is already freed (filled up with 0X5A). At this point the assert fires.

**Comment by yuslepukhin** [comment] 2016-08-18 23:55
This is caused by https://github.com/jemalloc/jemalloc/commit/09d7bdb314ec4d6a8618d6958809b540f8d3cff6

**Comment by jasone** [comment] 2016-10-21 07:33
This is likely resolved by e2bcf037d445a84a71c7997670819ebd0a893b4a.  If so, this is can be closed as a duplicate of #425.

**Comment by tkoecker** [comment] 2016-10-25 06:59
I've tried to reproduce the problem with the reproducer on issue #450 with the current 4.3.0 branch code. I did not get any crash anymore.

**Comment by jasone** [comment] 2016-10-25 14:48
Thanks @tkoecker!

Closing with the understanding that #425, #441, and #450 are all caused by the same underlying problem.

**Closed by jasone** 2016-10-25 14:48 UTC
Labels: bug, duplicate
