### ISSUE TITLE
jemalloc QNX 7.0 compatibility

### ISSUE THREAD

**Issue by pi1ot** [jemalloc/jemalloc#1632] opened 2019-09-19 07:01 UTC
jemalloc version: 5.2.1
QNX version: 7.0
Platform: ARM64(aarch64)
Build Tools: QNX Software Development Platform (SDP 7.0, ntoaarch64-g++, ntoaarch64-gcc)

Any code linked with libjemalloc.so will infinite loop at libgcc/emutls.c:159 and crash.

GDB backtrace
<img width="976" alt="je" src="https://user-images.githubusercontent.com/1677644/65220902-613d7500-daee-11e9-989d-f1bf110384ce.png">

libgcc/emutls.c:159
<img width="593" alt="Screen Shot 2019-09-19 at 14 33 40" src="https://user-images.githubusercontent.com/1677644/65220914-68fd1980-daee-11e9-842f-1de912ec5f4c.png">

**Comment by interwq** [comment] 2019-09-30 18:52
It's caused by the circular dependency between getting thread local storage and calloc. I'n not sure if it's possible to support the libgcc integration here -- @davidtgoldblatt do you have any context with libgcc and QNX?

**Comment by davidtgoldblatt** [comment] 2019-09-30 19:02
I've looked at jemalloc/QNX bugs before, but don't recall the details. Just from the bug it looks like we should try to detect QNX at build time and treat it as not having `__thread` support (instead going down the pthread_getspecific tsd implementation).

**Comment by interwq** [comment] 2019-09-30 19:52
@pi1ot : we don't have QNX support at the moment; we'll be happy accept patches though. As David mentioned, one thing should to be changed is the TLS model; however it's hard to say what else is needed.

**Comment by interwq** [comment] 2019-09-30 19:53
Closing as we have #1169 already.

**Closed by interwq** 2019-09-30 19:53 UTC
Labels: portability

**Comment by pi1ot** [comment] 2019-09-30 22:47
Can I disable TLS by myself?

**Comment by hbwang15** [comment] 2021-09-02 11:29
> Can I disable TLS by myself?

are you succeed in porting jemalloc? if so, can you help me by giving the steps of you work.

**Comment by pi1ot** [comment] 2021-09-02 11:35
> > Can I disable TLS by myself?
> are you succeed in porting jemalloc? if so, can you help me by giving the steps of you work.

no.

**Comment by hbwang15** [comment] 2021-09-02 11:38
any other malloc options or any advices. we really want to change to origin malloc in qnx.

**Comment by hbwang15** [comment] 2021-09-02 11:40
> > > Can I disable TLS by myself?
> > > are you succeed in porting jemalloc? if so, can you help me by giving the steps of you work.
> 
> no.

do you have any other optional opensource malloc which you have ported success? or any advices ?  i really want change the origin malloc in qnx 7.0.

**Comment by pi1ot** [comment] 2021-09-02 11:44
> > > > Can I disable TLS by myself?
> > > > are you succeed in porting jemalloc? if so, can you help me by giving the steps of you work.
> > 
> > 
> > no.
> 
> do you have any other optional opensource malloc which you have ported success? or any advices ? i really want change the origin malloc in qnx 7.0.

no, sorry.

**Comment by hbwang15** [comment] 2021-09-02 14:04
> > > > > Can I disable TLS by myself?
> > > > > are you succeed in porting jemalloc? if so, can you help me by giving the steps of you work.
> > > 
> > > 
> > > no.
> > 
> > 
> > do you have any other optional opensource malloc which you have ported success? or any advices ? i really want change the origin malloc in qnx 7.0.
> 
> no, sorry.

hey， could you help me with this compiler error?

![企业微信截图_16305914353537](https://user-images.githubusercontent.com/65098776/131857982-6801d4eb-a3bd-4eaf-a9d4-7a55a8c407f7.png)

**Comment by hbwang15** [comment] 2021-09-02 14:05
my configure command is : 

./configure CC="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-gcc" CXX="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-g++" CFLAGS="--sysroot=/workspaces/mfrnode/cdc_mfr_node/.build/saic/_deps/cc_toolchain/qnx700/target/qnx7/aarch64le -fPIC -fPIE -pthread -D_QNX_SOURCE  -O3 -DNDEBUG -pthread" --disable-syscall --target=aarch64-qnx-qnx --host=x86_64-linux-gnu RANLIB="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ranlib" AR="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ar" LD="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ld" LDCXX="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ld

**Comment by pi1ot** [comment] 2021-09-03 01:30
> my configure command is :
> 
> ./configure CC="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-gcc" CXX="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-g++" CFLAGS="--sysroot=/workspaces/mfrnode/cdc_mfr_node/.build/saic/_deps/cc_toolchain/qnx700/target/qnx7/aarch64le -fPIC -fPIE -pthread -D_QNX_SOURCE -O3 -DNDEBUG -pthread" --disable-syscall --target=aarch64-qnx-qnx --host=x86_64-linux-gnu RANLIB="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ranlib" AR="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ar" LD="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ld" LDCXX="${QNX_BINS}/aarch64-unknown-nto-qnx7.0.0-ld

my compile options just only "-D_QNX_SOURCE", no other options, grep QNX src for error keyword maybe useful.
