### ISSUE TITLE
Heap profiling shows 100% je_prof_backtrace

### ISSUE THREAD

**Issue by mbohy** [jemalloc/jemalloc#507] opened 2016-11-21 21:28 UTC
We have a multi-threaded production Java web application using embedded tomcat, which is exhibiting signs of a native memory leak.  The application is managed by the Java Service Wrapper (http://wrapper.tanukisoftware.com/doc/english/download.jsp), which may turn out to be relevant.

I'm attempting to locate the leak using examples others have posted on the web, e.g. http://www.evanjones.ca/java-native-leak-bug.html.  I am currently sanity-testing the jemalloc setup in an environment that does not have the leak.  Here is my configuration:

LD_PRELOAD=libjemalloc.so.1
MALLOC_CONF=prof:true,lg_prof_interval:30,lg_prof_sample:17

I built jemalloc from source using git SHA f7ca1c9bc321feffe056f5d154c287f63e324020, dated Wed Nov 16 19:41:09 2016 -0800.

I've collected 449 heap profiles over the past 4 days.  When using jeprof to analyze the profiles, I invariably see 100% of the memory used (or allocated by?) what seems to be jemalloc itself:

`perl bin/jeprof --show_bytes --text <path_to_java_executable><path_to_heap_profiles>/jeprof.3285.* > output.txt`

`cat output.txt
Total: 127759580182 B
127759580182 100.0% 100.0% 127759580182 100.0% je_prof_backtrace`

Obviously without a leak present, I may not see anything very interesting, but I was expecting to at least see traces related to the JVM, if not related to my application.

I understand that my MALLOC_CONF may be wrong for my use case, but something still seems fundamentally wrong if I'm only seeing je_prof_backtrace.  Could the fact that this process is started by the Java Service Wrapper be relevant, or perhaps because the application is not single-threaded?

Any help would be greatly appreciated!

**Comment by interwq** [comment] 2016-11-21 22:13
@mbohy: heap profiling gives you the full stack trace when the sample is taken. That means prof_backtrace (which invokes stack unwinding and gets the trace) is almost always the top element on the stack, assuming it's not inlined. To utilize the stack trace from profiling, you will need to look further onto the stack. For example, a trace may look like:
... ==> some_function_in_application ==> je_malloc  ==> je_prof_backtrace
in which case you may want to focus on the functions  in the application instead of allocator. Similarly, it's also common to see operator new or equivalent in the runtime.

**Comment by mbohy** [comment] 2016-11-21 22:28
@interwq Thanks very much for the quick reply!

That all makes sense, except I don't see any other stack information.  I literally see one element (je_prof_backtrace) when I do any kind of summary analysis (pdf, text, png) using jeprof.

In my initial description above I included the output of the --text analysis, which you can see just has one element in it.  Is there something I need to do to get the analysis to include more elements from the sampled traces?

**Comment by jasone** [comment] 2016-11-21 22:30
Adding to what @interwq said, the ```jeprof``` script strips out frames that match certain patterns, but since you are using a ```je_``` prefix, those patterns aren't matching.  Perhaps the ```jeprof``` script should be enhanced to handle this case.  In the meanwhile you can modify ```jeprof``` -- look for e.g. ```mallocx``` and modify the list it's part of.

**Comment by jasone** [comment] 2016-11-30 19:10
Marking as a bug in jeprof.  This should be simple to resolve, since jeprof.in is already processed by configure and @...@ substitution can be trivially used.

**Comment by mbohy** [comment] 2016-12-08 18:56
@jasone Thanks for taking a close look at this.  I've added some debug statements to my copy of jeprof and from what I can tell the profiles themselves only have the je_prof_backtrace symbol in them.

Here's an example run of my script with 11 profiles, including my debug statements (prefixed with "MB: "):
```
[root@centos65 bin]# perl /root/jemalloc/bin/jeprof --show_bytes --text /glide/java-1.8.0_112.i586/bin/java jeprof.6750.9*.heap
Using local file /glide/java-1.8.0_112.i586/bin/java.
Using local file jeprof.6750.9.i9.heap.
Using local file jeprof.6750.99.i99.heap.
Using local file jeprof.6750.98.i98.heap.
Using local file jeprof.6750.97.i97.heap.
Using local file jeprof.6750.96.i96.heap.
Using local file jeprof.6750.95.i95.heap.
Using local file jeprof.6750.94.i94.heap.
Using local file jeprof.6750.93.i93.heap.
Using local file jeprof.6750.92.i92.heap.
Using local file jeprof.6750.91.i91.heap.
Using local file jeprof.6750.90.i90.heap.
Fetching 11 profiles, Be patient...
Using local file jeprof.6750.9.i9.heap.
Using local file jeprof.6750.99.i99.heap.
Using local file jeprof.6750.98.i98.heap.
Using local file jeprof.6750.96.i96.heap.
Using local file jeprof.6750.92.i92.heap.
Using local file jeprof.6750.97.i97.heap.
Using local file jeprof.6750.95.i95.heap.
Using local file jeprof.6750.94.i94.heap.
Using local file jeprof.6750.90.i90.heap.
Using local file jeprof.6750.91.i91.heap.
Using local file jeprof.6750.93.i93.heap.
MB: Read first profile
MB: Read additional profile jeprof.6750.9.i9.heap
MB: Read additional profile jeprof.6750.99.i99.heap
MB: Read additional profile jeprof.6750.98.i98.heap
MB: Read additional profile jeprof.6750.97.i97.heap
MB: Read additional profile jeprof.6750.96.i96.heap
MB: Read additional profile jeprof.6750.95.i95.heap
MB: Read additional profile jeprof.6750.94.i94.heap
MB: Read additional profile jeprof.6750.93.i93.heap
MB: Read additional profile jeprof.6750.92.i92.heap
MB: Read additional profile jeprof.6750.91.i91.heap
MB: About to FilterAndPrint
MB: Processing key 00000000003aada5
MB: Processing address 00000000003aada5
MB: Found func in symbols je_prof_backtrace
Total: 4767774157 B
4767774157 100.0% 100.0% 4767774157 100.0% je_prof_backtrace
MB: Thread is 1
MB: Thread is 4
MB: Thread is 9
MB: Thread is 10
MB: Thread is 11
MB: Thread is 16
MB: Thread is 17
MB: Thread is 18
MB: Thread is 21
MB: Thread is 28
MB: Thread is 32
MB: Thread is 35
MB: Thread is 38
MB: Thread is 39
MB: Thread is 40
MB: Thread is 41
MB: Thread is 67
MB: Thread is 68
MB: Thread is 90
MB: Thread is 95
MB: Thread is 99
MB: Thread is 187
MB: Thread is 5091
If you want to investigate this profile further, you can do:

  jeprof \
    /glide/java-1.8.0_112.i586/bin/java \
    jeprof.6750.9.i9.heap \
    jeprof.6750.99.i99.heap \
    jeprof.6750.98.i98.heap \
    jeprof.6750.97.i97.heap \
    jeprof.6750.96.i96.heap \
    jeprof.6750.95.i95.heap \
    jeprof.6750.94.i94.heap \
    jeprof.6750.93.i93.heap \
    jeprof.6750.92.i92.heap \
    jeprof.6750.91.i91.heap \
    jeprof.6750.90.i90.heap

```
I've attached the profiles here: [profiles.zip](https://github.com/jemalloc/jemalloc/files/640316/profiles.zip)

Here is my modified version of jeprof: 
[jeprof_debug.txt](https://github.com/jemalloc/jemalloc/files/640322/jeprof_debug.txt)

When I look at the profile files, the only symbol address I see is 0x3aada5, which (as shown above) gets mapped to je_prof_backtrace.  So it seems like the profiles themselves only contain this symbol, rather than that the jeprof script is filtering out other symbols.  But of course, I may be way off there.

Assuming I'm misunderstanding something though, I'd be happy to try rebuilding with a different prefix, as you mentioned "since you are using a je_ prefix".  I don't care about the prefix at all, so if I did something strange while building, it was out of ignorance.  Do you mind telling me the "normal" way to build that might avoid this issue in the first place?  (Assuming what I've concluded above about jeprof is incorrect, of course.)

Thank you @jasone!
- Matt

**Comment by jasone** [comment] 2016-12-08 22:55
@mbohy, you're correct that the heap profiles do not contain full backtraces.  This is usually caused by the backtracing facility failing to do anything beyond reporting the caller's return instruction pointer.  You may have better luck if you use libunwind, but unfortunately I've seen *all* the supported backtracing mechanisms fail under various conditions.

Note that the [heap profile format](http://jemalloc.net/jemalloc.3.html#heap_profile_format) is documented in the man page, and a quick look at that documentation will enable you to directly look at heap profiles and tell if something is amiss.

**Comment by mbohy** [comment] 2017-01-05 00:04
@jasone thanks for confirming what I saw.

The saga continues. :|

I've been struggling with libunwind to get it to work with jemalloc, but I'm wondering if I'm going down a dead end.  A piece of information I left out earlier is that the JVM I'm trying to trace is the 32-bit version of the JVM, which means I had to build jemalloc as 32-bit, and (I believe) I'd need the 32-bit version of libunwind.  But when I try to configure/make jemalloc to use libunwind, it doesn't recognize the library because it can't find the unw_backtrace symbol.  I used "nm" on the binaries and indeed it seems like the symbol is only in the 64-bit version of the library.

So that leads to these questions:
1. Is it supported to build a 32-bit jemalloc?
2. Does jemalloc work with a 32-bit libunwind?

Thank you!
Matt

**Comment by mbohy** [comment] 2017-01-05 08:49
I've built both jemalloc and libunwind 1.1 on a 32-bit VM, which seems to have avoided some of the clunkiness of trying to build 32-bit on a 64-bit machine.  So jemalloc is using libunwind now, but unfortunately now the process segfaults immediately after getting the first sample.  The sample does have full stack traces now, at least. :\

I've reached out to the libunwind mailing list for help on the segfault.  Meanwhile I will try one of the other backtracing methods (I think there's only one left that I can try).

**Closed** 2017-05-31 03:22 UTC
Labels: bug, profiling

**Comment by komarios** [comment] 2017-06-23 07:48
Hi,
I am facing the same problem on ubuntu for arm (aarch64) on a raspberry clone (odroid c2).
I want to find a java jni memory leak for tomcat 8.0.44 with java1.8.131
But running jeprof yields 100% of je_prof_backtrace.
My other tests with ubuntu on x86_64 are running fine by the way!
Should I open a new issue?
What other info should I provide you with?
