### ISSUE TITLE
Why is stats.active much greater than stats.allocated?

### ISSUE THREAD

**Issue by luobing2023** [jemalloc/jemalloc#2461] opened 2023-06-15 10:42 UTC
I am running a server program that embeds a Lua virtual machine, which creates temporary many strings in Lua virtual machine and allocates a large amount of memory. After a period of time, Although the memory occupied by the Lua virtual machine has been reduced after Lua's garbage collection, the memory usage shown by the "top" command does not decrease.

The version of jemalloc I am using is 5.3.0, with background_thread:true.

```
Arenas: 33
Quantum size: 16
Page size: 4096
Maximum thread-cached size class: 32768
Number of bin size classes: 36
Number of thread-cache bin size classes: 41
Number of large size classes: 196
Allocated: 2763034152, active: 6373089280, metadata: 111765568 (n_thp 0), resident: 6484914176, mapped: 6494924800, retained: 5014245376
Count of realloc(non-null-ptr, 0) calls: 0
Background threads: 3, num_runs: 450, run_interval: 2340108626 ns
Merged arenas stats:
assigned threads: 3
uptime: 531099995325
dss allocation precedence: "N/A"
decaying:  time       npages       sweeps     madvises       purged
   dirty:   N/A           49          337        81352      1189377
   muzzy:   N/A            0            0            0            0
                            allocated         nmalloc   (#/sec)         ndalloc   (#/sec)       nrequests   (#/sec)           nfill   (#/sec)          nflush   (#/sec)
small:                     2460794408       118115642    222440        93008008    175156       180629760    340169         1645332      3098         1116271      2102
large:                      302239744            6096        11            5481        10           58952       111            6096        11            1720         3
total:                     2763034152       118121738    222451        93013489    175166       180688712    340280         1651428      3110         1117991      2105
                                     
active:                    6373089280
mapped:                    6494924800
retained:                  5014245376
base:                       111614016
internal:                      151552
metadata_thp:                       0
tcache_bytes:                  407960
tcache_stashed_bytes:               0
resident:                  6484914176
abandoned_vm:                       0
extent_avail:                  147744
bins:           size ind    allocated      nmalloc (#/sec)      ndalloc (#/sec)    nrequests   (#/sec)  nshards      curregs     curslabs  nonfull_slabs regs pgs   util       nfills (#/sec)     nflushes (#/sec)       nslabs     nreslabs (#/sec)
                   8   0       424088        61585     115         8574      16       319749       602        1        53011          106              1  512   1  0.976        14774      27         1137       2          116          213       0
                  16   1       133680        20276      38        11921      22       366670       690        1         8355           35              6  256   1  0.932        12222      23         2073       3           64          200       0
                  32   2     30418048     14015200   26393     13064636   24603     31837420     59957        1       950564        69265          64147  128   1  0.107       163125     307       134257     252        87506        37170      70
                  48   3    193818912     20715238   39011     16677344   31407     37568143     70749        1      4037894        48608          37206  256   3  0.324       255949     482       168380     317        49109        80812     152
                  64   4     59621248      4091976    7706      3160394    5951      6730132     12674        1       931582        39877          38564   64   1  0.365        78566     147        51852      97        41886        42840      80
                  80   5   1226406080     61449917  115724     46119841   86854     69713049    131286        1     15330076       161203         123826  256   5  0.371       685562    1291       462854     871       171057       146151     275
                  96   6    138527616      4793166    9026      3350170    6309     15241927     28704        1      1442996        15431           4380  128   3  0.730        66302     124        36985      69        27704        22046      41
                 112   7     12854016       204707     385        89939     169       198993       374        1       114768          492             43  256   7  0.911        13919      26         4029       7          721          613       1
                 128   8      6643712        63209     119        11305      21       495798       933        1        51904         1623              0   32   1  0.999         6309      11         1605       3         1901          184       0
                 160   9     20416160       327259     616       199658     376       650497      1225        1       127601         1226            299  128   5  0.813         9992      18         7285      13         1604         2596       4
                 192  10    164861184      9039642   17023      8180990   15406     11126868     20954        1       858652        61437          54721   64   3  0.218       158193     297       131256     247       116448        40506      76
                 224  11     15548512       231137     435       161724     304       244115       459        1        69413          544              0  128   7  0.996         6486      12         4542       8         1319         1274       2
                 256  12      2462464        63268     119        53649     101      1596213      3006        1         9619          616             15   16   1  0.975         7605      14         5587      10         1841         8986      16
                 320  13     48650560       434061     817       282028     531       439782       828        1       152033         3698           1486   64   5  0.642        11509      21         7672      14         4157         5117       9
                 384  14    281101824      1764206    3322      1032170    1943      2087405      3931        1       732036        25836          14021   32   3  0.885        64123     120        34340      64        35456        60718     114
                 448  15      4063808        75781     142        66710     125       109656       206        1         9071          213             79   64   7  0.665         4608       8         3824       7          709         1849       3
                 512  16      4009984        44568      83        36736      69       257028       484        1         7832         1017             44    8   1  0.962         8353      15         5399      10         2831         6330      11
                 640  17     11038080        40482      76        23235      43        61234       115        1        17247          540              1   32   5  0.998         3867       7         2406       4         1102          904       1
                 768  18    100054272       305413     575       175134     329       322878       608        1       130279        13114           9949   16   3  0.620        23813      44        12657      23        13977        12115      22
                 896  19      5112576        22984      43        17278      32        21247        40        1         5706          180              5   32   7  0.990         2285       4         2266       4          584          560       1
                1024  20      4260864        19706      37        15545      29       202005       380        1         4161         1042              1    4   1  0.998         3017       5         2456       4         4804          694       1
                1280  21      8354560        18697      35        12170      22        17818        33        1         6527          409              0   16   5  0.997         2423       4         1691       3         1067          700       1
                1536  22     21596160        34039      64        19979      37        35431        66        1        14060         1758              1    8   3  0.999         5345      10         2861       5         3434         1677       3
                1792  23      8010240        13029      24         8559      16        10277        19        1         4470          281              0   16   7  0.994         1571       2         1306       2          796          226       0
                2048  24     36904960        42833      80        24813      46       143493       270        1        18020         9011              1    2   1  0.999         5157       9         3093       5        21353          550       1
                2560  25     36866560        33313      62        18912      35        33046        62        1        14401         1801              0    8   5  0.999         4140       7         2403       4         4085          356       0
                3072  26     14509056         7007      13         2284       4         7282        13        1         4723         1182              2    4   3  0.998         1633       3          859       1         1511          593       1
                3584  27       569856          381       0          222       0          307         0        1          159           20              0    8   7  0.993          138       0          128       0           46           32       0
                4096  28        73728       168607     317       168589     317       198910       374        1           18           18              0    1   1      1        20094      37        17294      32       168607            0       0
                5120  29       604160         1073       2          955       1         1021         1        1          118           34              6    4   5  0.867          441       0          394       0          131          372       0
                6144  30      1118208          944       1          762       1         2764         5        1          182          110             37    2   3  0.827          441       0          412       0          308          201       0
                7168  31        57344          128       0          120       0           79         0        1            8            2              0    4   7      1           61       0           79       0           35           13       0
                8192  32        73728        10010      18        10001      18        77380       145        1            9            9              0    1   2      1         2221       4         1818       3        10010            0       0
               10240  33       471040          965       1          919       1       510090       960        1           46           24              0    2   5  0.958          599       1          601       1          381          294       0
               12288  34      1056768          764       1          678       1         1017         1        1           86           86              0    1   3      1          461       0          435       0          764            0       0
               14336  35       100352           71       0           64       0           36         0        1            7            4              0    2   7  0.875           28       0           35       0           37           10       0
large:          size ind    allocated      nmalloc (#/sec)      ndalloc (#/sec)    nrequests (#/sec)  curlextents
               16384  36       131072          325       0          317       0          560       1            8
               20480  37      3747840          509       0          326       0          553       1          183
               24576  38      1622016          610       1          544       1          767       1           66
               28672  39       229376           43       0           35       0           44       0            8
               32768  40        98304          976       1          973       1        53395     100            3
               40960  41       163840          120       0          116       0          120       0            4
               49152  42      9043968          572       1          388       0          572       1          184
               57344  43        57344           24       0           23       0           24       0            1
               65536  44       131072          298       0          296       0          298       0            2
               81920  45       409600           62       0           57       0           62       0            5
               98304  46      2555904          147       0          121       0          147       0           26
              114688  47       114688           18       0           17       0           18       0            1
              131072  48       262144          272       0          270       0          272       0            2
              163840  49       163840           40       0           39       0           40       0            1
              196608  50      3145728           93       0           77       0           93       0           16
              229376  51            0            6       0            6       0            6       0            0
              262144  52            0          234       0          234       0          234       0            0
              327680  53      1310720           28       0           24       0           28       0            4
              393216  54      2752512           56       0           49       0           56       0            7
              458752  55            0            5       0            5       0            5       0            0
              524288  56       524288          222       0          221       0          222       0            1
              655360  57      3932160           70       0           64       0           70       0            6
              786432  58      1572864           32       0           30       0           32       0            2
              917504  59            0            4       0            4       0            4       0            0
             1048576  60      3145728          239       0          236       0          239       0            3
             1310720  61      1310720           13       0           12       0           13       0            1
             1572864  62      3145728           53       0           51       0           53       0            2
             1835008  63    128450560          435       0          365       0          435       0           70
             2097152  64            0          518       0          518       0          518       0            0
             2621440  65            0            8       0            8       0            8       0            0
             3145728  66      6291456           12       0           10       0           12       0            2
                     ---
             4194304  68            0            8       0            8       0            8       0            0
             5242880  69     10485760            9       0            7       0            9       0            2
             6291456  70            0            4       0            4       0            4       0            0
             7340032  71            0            2       0            2       0            2       0            0
             8388608  72            0            2       0            2       0            2       0            0
            10485760  73            0            2       0            2       0            2       0            0
            12582912  74     50331648            4       0            0       0            4       0            4
            14680064  75            0            2       0            2       0            2       0            0
            16777216  76            0            3       0            3       0            3       0            0
            20971520  77            0            2       0            2       0            2       0            0
            25165824  78            0            2       0            2       0            2       0            0
                     ---
            33554432  80            0            1       0            1       0            1       0            0
            41943040  81            0            1       0            1       0            1       0            0
                     ---
            67108864  84     67108864            1       0            0       0            1       0            1
            83886080  85            0            4       0            4       0            4       0            0
                     ---
           167772160  89            0            2       0            2       0            2       0            0
                     ---
           536870912  96            0            2       0            2       0            2       0            0
           671088640  97            0            1       0            1       0            1       0            0
                     ---
extents:        size ind       ndirty        dirty       nmuzzy        muzzy    nretained     retained       ntotal        total
                4096   0            1         4096            0            0         4310     17653760         4311     17657856
                8192   1            0            0            0            0          322      2637824          322      2637824
               12288   2            3        36864            0            0        28861    354643968        28864    354680832
               16384   3            3        49152            0            0         7139    116965376         7142    117014528
               20480   4            1        20480            0            0         1441     29511680         1442     29532160
               24576   5            0            0            0            0         3224     79233024         3224     79233024
               28672   6            2        57344            0            0          912     26148864          914     26206208
               32768   7            1        32768            0            0         3277    113422336         3278    113455104
               40960   8            0            0            0            0          550     24064000          550     24064000
               49152   9            0            0            0            0          853     43118592          853     43118592
               57344  10            0            0            0            0          382     22368256          382     22368256
               65536  11            0            0            0            0          605     42704896          605     42704896
               81920  12            0            0            0            0          356     30416896          356     30416896
               98304  13            0            0            0            0          143     15159296          143     15159296
              114688  14            0            0            0            0           65      7938048           65      7938048
              131072  15            0            0            0            0           69      9900032           69      9900032
              163840  16            0            0            0            0           34      5959680           34      5959680
              196608  17            0            0            0            0           15      3112960           15      3112960
              229376  18            0            0            0            0           11      2711552           11      2711552
              262144  19            0            0            0            0           18      5279744           18      5279744
              327680  20            0            0            0            0           13      4571136           13      4571136
              393216  21            0            0            0            0            2       827392            2       827392
              458752  22            0            0            0            0            6      2924544            6      2924544
              524288  23            0            0            0            0           10      5758976           10      5758976
              655360  24            0            0            0            0            2      1486848            2      1486848
              786432  25            0            0            0            0            2      1658880            2      1658880
              917504  26            0            0            0            0            4      3842048            4      3842048
             1048576  27            0            0            0            0            3      3309568            3      3309568
             1310720  28            0            0            0            0            4      5521408            4      5521408
             1572864  29            0            0            0            0            8     13885440            8     13885440
             1835008  30            0            0            0            0            1      2064384            1      2064384
                     ---
             2621440  32            0            0            0            0            1      3084288            1      3084288
                     ---
             3670016  34            0            0            0            0            1      3670016            1      3670016
             4194304  35            0            0            0            0            1      4194304            1      4194304
             5242880  36            0            0            0            0            1      5242880            1      5242880
             6291456  37            0            0            0            0            1      6291456            1      6291456
             7340032  38            0            0            0            0            1      7340032            1      7340032
             8388608  39            0            0            0            0            1      8388608            1      8388608
            10485760  40            0            0            0            0            1     10485760            1     10485760
            12582912  41            0            0            0            0            2     25165824            2     25165824
            14680064  42            0            0            0            0            1     14680064            1     14680064
            16777216  43            0            0            0            0            1     16777216            1     16777216
            20971520  44            0            0            0            0            1     20971520            1     20971520
            25165824  45            0            0            0            0            1     25165824            1     25165824
            29360128  46            0            0            0            0            2     60817408            2     60817408
            33554432  47            0            0            0            0            2     67108864            2     67108864
            41943040  48            0            0            0            0            2     89907200            2     89907200
            50331648  49            0            0            0            0            3    159649792            3    159649792
            58720256  50            0            0            0            0            1     58720256            1     58720256
            67108864  51            0            0            0            0            1     67108864            1     67108864
            83886080  52            0            0            0            0            1     83886080            1     83886080
                     ---
           201326592  57            0            0            0            0            1    201326592            1    201326592
                     ---
           536870912  63            0            0            0            0            1    536870912            1    536870912
           671088640  64            0            0            0            0            1    671088640            1    671088640
           805306368  65            0            0            0            0            1    805306368            1    805306368
           939524096  66            0            0            0            0            1   1062195200            1   1062195200
                     ---
Bytes in small extent cache: 0
HPA shard stats:
  Purge passes: 0 (0 / sec)
  Purges: 0 (0 / sec)
  Hugeifies: 0 (0 / sec)
  Dehugifies: 0 (0 / sec)

  In full slabs:
      npageslabs: 0 huge, 0 nonhuge
      nactive: 0 huge, 0 nonhuge 
      ndirty: 0 huge, 0 nonhuge 
      nretained: 0 huge, 0 nonhuge 
  In empty slabs:
      npageslabs: 0 huge, 0 nonhuge
      nactive: 0 huge, 0 nonhuge 
      ndirty: 0 huge, 0 nonhuge 
      nretained: 0 huge, 0 nonhuge 

                size ind npageslabs_huge    nactive_huge     ndirty_huge  npageslabs_nonhuge     nactive_nonhuge      ndirty_nonhuge   nretained_nonhuge
                     ---
```

[jemalloc_stats_print.txt](https://github.com/jemalloc/jemalloc/files/11756523/jemalloc_stats_print.txt)

**Comment by interwq** [comment] 2023-06-16 01:56
The workload has super bad fragmentation, e.g. the 80-byte size class has allocated of 1226406080, but `util` is only 0.371, indicating >2G of memory are fragmented.

You will want to identify the fragmenting workloads, and fixing that. Typically this is caused by, allocating a ton of objects, then free 99% of those randomly and quickly, but keeping the remaining 1% long lived -- this cause many physical pages to be partially used, and thus the high fragmentation.

Closing but feel free to ask questions.

**Closed as completed by interwq** 2023-06-16 01:56 UTC
Labels: question
