### ISSUE TITLE
spinning on an atomic leaks memory when using jemalloc

### ISSUE THREAD

**Issue by amosbird** [jemalloc/jemalloc#1347] opened 2018-10-17 02:34 UTC
When keeping spawning new threads doing this spin and exits, process RSS keeps going up and finally gets OOM killed when linking with jemalloc. libc malloc doesn't have this problem.  
```
#include <atomic>
#include <thread>
#include <deque>
#include <chrono>

inline int do_spin(std::atomic<unsigned> & generation, unsigned int val)
{
    for (;;)
        if (generation.load(std::memory_order_relaxed) != val)
            return 0;
}

int main(int argc, char *argv[]) {
    std::atomic<unsigned> generation = 0;
    for(;;) {
        std::deque<std::thread> q;
        for (auto i = 1u; i < 40; ++i) {
            q.push_back(std::thread([&]() {
                do_spin(generation, generation);
            }));
        }
        using namespace std::chrono_literals;
        std::this_thread::sleep_for(100ms);
        generation ++;
        for (auto & t : q) {
            t.join();
        }
    }
}
```

**Comment by interwq** [comment] 2018-10-30 22:47
@amosbird thanks for the report. Can you please share the platform info and the jemalloc config?

**Comment by amosbird** [comment] 2018-10-31 01:50
it's centos 7 x64, with default jemalloc config.

**Comment by amosbird** [comment] 2018-11-03 03:10
@interwq https://la.wentropy.com/SRVF

**Comment by interwq** [comment] 2018-11-08 20:32
Took me a while to realize this was a decay related issue. Focused only on thread cleanup which was fine. This is resolved by #1366.

This is a rather edge case, and triggers a pathological case in the [decay based purging](http://jemalloc.net/jemalloc.3.html#opt.dirty_decay_ms). Normally when there's active allocation activities, the decay is triggered properly. However in this case, the thread shutdown path didn't properly tick the decay and required some additional handling.

**Closed** 2018-11-09 19:03 UTC
Labels: bug

**Comment by alexey-milovidov** [comment] 2019-01-09 19:51
Performance degradation is not necessarily related to this patch.
It is related to something between these revisions:
https://github.com/jemalloc/jemalloc/compare/41b7372eadee941b9164751b8d4963f915d3ceae...cd2931ad9bbd78208565716ab102e86d858c2fff
Jemalloc suddenly started to call mmap to frequently for realloc (in this stack trace you see realloc from 4096 to 16384 bytes - such a small memory chunk should be usually cached in allocator).

**Comment by interwq** [comment] 2019-01-09 20:06
@alexey-milovidov @amosbird thanks for reporting this! The stack trace itself doesn't really ring any bell. If it reproduces reliably, can you guys please help to bisect to the diff, given that you have an accurate range?

**Comment by alexey-milovidov** [comment] 2019-01-10 13:52
This commit makes the regression:

https://github.com/jemalloc/jemalloc/commit/7ee0b6cc37ecbecf8f53ba46326258275053ca50

**Comment by alexey-milovidov** [comment] 2019-01-10 14:57
Reproducing test:

```
#include <cstdlib>
#include <cstring>
#include <vector>
#include <thread>


void thread_func()
{
    for (size_t i = 0; i < 100; ++i)
    {
        size_t size = 4096;

        void * buf = malloc(size);
        if (!buf)
            abort();
        memset(buf, 0, size);

        while (size < 1048576)
        {
            size_t next_size = size * 4;

            void * new_buf = realloc(buf, next_size);
            if (!new_buf)
                abort();
            buf = new_buf;

            memset(reinterpret_cast<char*>(buf) + size, 0, next_size - size);
            size = next_size;
        }

        free(buf);
    }
}


int main(int, char **)
{
    std::vector<std::thread> threads(16);
    for (size_t i = 0; i < 1000; ++i)
    {
        for (auto & thread : threads)
            thread = std::thread(thread_func);
        for (auto & thread : threads)
            thread.join();
    }
    return 0;
}
```

We create and destroy some threads that do malloc, reallocs and free in a loop.

Bad revision: 7ee0b6c
Good revision: d66f976

```
$ strace -f -e trace=mmap ./realloc-perf-7ee0b6c 2>&1 | wc -l
506763
$ strace -f -e trace=mmap ./realloc-perf-d66f976 2>&1 | wc -l
44607
```

```
$ time ./realloc-perf-7ee0b6c

real    0m16.928s
user    3m10.116s
sys     0m15.908s

$ time ./realloc-perf-d66f976 

real    0m13.921s
user    1m6.660s
sys     0m0.552s
```
(note "sys" time)

```
sudo perf record -a ./realloc-perf-7ee0b6c
sudo perf report

  74.68%  realloc-perf-7e  libc-2.19.so                 [.] memset
   8.71%  swapper          [kernel.kallsyms]            [k] intel_idle
   4.77%  realloc-perf-7e  [kernel.kallsyms]            [k] native_write_msr_safe
   1.49%  swapper          [kernel.kallsyms]            [k] native_write_msr_safe
   0.79%  realloc-perf-7e  [kernel.kallsyms]            [k] osq_lock
   0.78%  realloc-perf-7e  [kernel.kallsyms]            [k] clear_page_c_e
   0.65%  realloc-perf-7e  libpthread-2.19.so           [.] pthread_mutex_trylock
   0.60%  realloc-perf-7e  libpthread-2.19.so           [.] pthread_mutex_unlock
   0.43%  realloc-perf-7e  [kernel.kallsyms]            [k] unmap_single_vma
   0.43%  realloc-perf-7e  realloc-perf-7ee0b6c         [.] arena_extent_ralloc_large_expand
   0.43%  realloc-perf-7e  [kernel.kallsyms]            [k] page_remove_rmap
   0.43%  realloc-perf-7e  realloc-perf-7ee0b6c         [.] hook_invoke_expand
   0.43%  perf             [kernel.kallsyms]            [k] native_write_msr_safe
   0.41%  realloc-perf-7e  [kernel.kallsyms]            [k] handle_mm_fault
```

```
sudo perf record -a ./realloc-perf-d66f976
sudo perf report

  55.37%  realloc-perf-d6  libc-2.19.so          [.] memset
  28.07%  swapper          [kernel.kallsyms]     [k] intel_idle
   9.19%  realloc-perf-d6  [kernel.kallsyms]     [k] native_write_msr_safe
   2.30%  swapper          [kernel.kallsyms]     [k] native_write_msr_safe
   0.77%  realloc-perf-d6  [kernel.kallsyms]     [k] put_dec
   0.52%  realloc-perf-d6  realloc-perf-d66f976  [.] arena_extent_alloc_large
   0.38%  realloc-perf-d6  realloc-perf-d66f976  [.] extent_split_impl.constprop.58
   0.38%  realloc-perf-d6  realloc-perf-d66f976  [.] realloc
   0.38%  realloc-perf-d6  realloc-perf-d66f976  [.] extent_recycle
   0.34%  realloc-perf-d6  realloc-perf-d66f976  [.] free
   0.34%  realloc-perf-d6  [kernel.kallsyms]     [k] llist_add_batch
```

**Comment by interwq** [comment] 2019-01-10 21:31
@alexey-milovidov : thanks a lot for the detailed report! Much appreciated.

However in this case, I'd consider the overhead to be associated with thread creation / termination; in other words creating new thread so frequently like in the benchmark is expected to be slow and not a case we really optimize for.

For more context, the specific commit 7ee0b6c does this: on the thread exit path, check if the current thread is the last one associated with the current arena, and if so, force purging all the cached extents, because otherwise we risk the cache being pooled there forever if no more threads are being created (as in the original issue).

However this also means, the next thread coming in to access the arena, it won't have the warmed up cache ready there, thus the higher costs from page faults etc. I'd consider this less of a concern, given that in a practical / non-microbenchmark workload we should avoid killing threads so often, instead we want to reuse them such as with a thread pool design. If you use the same set of threads handling the same workload, there won't be any measurable difference with that commit.

Thanks again for digging into the issue. Feel free to let us know if anything.

**Comment by alexey-milovidov** [comment] 2019-01-11 15:04
Thank you! The reason is perfectly clear.

In our code we use per-query thread pools. But for different queries, threads are created and desroyed (there is no global thread pool). Queries are usually not very short - about of tens of milliseconds. In our benchmark we see degradation from 85ms to 180ms (more than two times).

What should be considered is that thread creation/destruction itself is capable to perform in about 100 000 ops/sec in Linux. But mmap, page fault, munmap is about two orders of magnitude slower - just about 1000 ops/sec.

I don't insist you to fix this unusual case, because we will
- add a global thread pool;
- add our own allocator cache;
in our application.

**Comment by interwq** [comment] 2019-01-11 19:34
@alexey-milovidov : I just realized that one thing on our side could make things for you easier, the `background_thread` feature. The thread termination slow down can be avoided, if you apply the patch in https://github.com/jemalloc/jemalloc/pull/1405 and enable background threads, e.g. by adding an env var `MALLOC_CONF=background_thread:true` when running your program. That way the application threads don't have to purge all cache on exit, as jemalloc owned threads will take care of that (which will happen way less frequently in this case).

But yeah I agree having a global thread pool sounds like a great idea either way.
