### ISSUE TITLE
The test/integration/mallocx on old 32bit bug strikes back (segfault)

### ISSUE THREAD

**Issue by ingvarha** [jemalloc/jemalloc#497] opened 2016-11-09 19:04 UTC
Hi, it's me with the old 32bit redhat/clones bugs again. This time with a segfault:

=== test/integration/mallocx ===
test_overflow: pass
test/test.sh: line 22: 25228 Segmentation fault      (core dumped) ${t} /builddir/build/BUILD/jemalloc-4.3.1/ /builddir/build/BUILD/jemalloc-4.3.1/
Test harness error

This was a CentOS6/i686 mock (chroot) build on a Fedora host.

I don't know if it's worth anything, but running integration/mallocx with no MALLOC_CONF set, it goes through all the tests without errors.

Full build log and gdb backtrace attached

[epel-6-i386_build.log.txt](https://github.com/jemalloc/jemalloc/files/581582/epel-6-i386_build.log.txt)
[jemalloc.gdb.bt.txt](https://github.com/jemalloc/jemalloc/files/581583/jemalloc.gdb.bt.txt)

**Comment by jasone** [comment] 2016-11-09 22:27
Ah, the backtrace is useful, thanks!  This is probably a duplicate of #492, but I was unable to reproduce it.  FWIW, this is actually a different bug than the other one you reported. ;-)

**Comment by ingvarha** [comment] 2016-11-10 07:21
I can reproduce this on ppc32 (RHEL5/ppc) as well, so it is probably a general 32bit problem on older (though still supported) systems.

https://kojipkgs.fedoraproject.org//work/tasks/2069/16382069/build.log

**Comment by jasone** [comment] 2016-11-11 19:48
Thanks for the offline help getting mock set up, @ingvarha.  After a couple hours of fiddling, I finally have a live debuggable repro of this issue.  There may be more than one problem, but so far I've ascertained that ea9961acdbc9f7e2c95a3b55ce0ac1024af5d167 needs to be backported.

**Comment by jasone** [comment] 2016-11-12 08:00
b9408d77a63a54fd331f9b81c884f68e6d57f2e5 was the actual fix; 2cdf07aba971d1e21edc203e7d4073b6ce8e72b9 was unnecessary (and superseded by 1aeea0f39143a658caf34c44ac59cb7fc6bb5749).

**Closed by jasone** 2016-11-12 08:00 UTC
Labels: bug
