### ISSUE TITLE
master branch make error

### ISSUE THREAD

**Issue by submarineblue** [jemalloc/jemalloc#738] opened 2017-04-01 03:00 UTC
when make the latest master branch, it reports: make: *** No rule to make target `include/jemalloc/internal/malloc_io.h', needed by `src/jemalloc.pic.o'.  Stop.

**Comment by interwq** [comment] 2017-04-01 04:22
Hi, can you please share more information like compiler / platform etc so that we can reproduce the issue? Maybe also include the full output from ./configure & make

**Comment by submarineblue** [comment] 2017-04-07 11:06
compiler: gcc version 4.1.2 20080704 (Red Hat 4.1.2-55)

platform: CentOS release 5.4 (Final)

./configure result:
jemalloc version   : 4.5.0-0-g04380e79f1e2428bd0ad000bbc6e3d2dfc6b66a5
library revision   : 2

CONFIG             : 
CC                 : gcc
CONFIGURE_CFLAGS   : -std=gnu99 -Wall -Wsign-compare -pipe -g3 -fvisibility=hidden -O3 -funroll-loops
SPECIFIED_CFLAGS   : 
EXTRA_CFLAGS       : 
CPPFLAGS           : -D_GNU_SOURCE -D_REENTRANT
LDFLAGS            : 
EXTRA_LDFLAGS      : 
LIBS               : -lrt -lm  -lpthread
RPATH_EXTRA        : 

XSLTPROC           : /usr/bin/xsltproc
XSLROOT            : 

PREFIX             : /usr/local
BINDIR             : /usr/local/bin
DATADIR            : /usr/local/share
INCLUDEDIR         : /usr/local/include
LIBDIR             : /usr/local/lib
MANDIR             : /usr/local/share/man

srcroot            : 
abs_srcroot        : /data/xiongzhongting/tmp/jemalloc/
objroot            : 
abs_objroot        : /data/xiongzhongting/tmp/jemalloc/

JEMALLOC_PREFIX    : 
JEMALLOC_PRIVATE_NAMESPACE
                   : je_
install_suffix     : 
malloc_conf        : 
autogen            : 0
cc-silence         : 1
debug              : 0
code-coverage      : 0
stats              : 1
prof               : 0
prof-libunwind     : 0
prof-libgcc        : 0
prof-gcc           : 0
tcache             : 1
thp                : 0
fill               : 1
utrace             : 0
valgrind           : 0
xmalloc            : 0
munmap             : 0
lazy_lock          : 0
tls                : 1
cache-oblivious    : 1

make output:
make: *** No rule to make target `include/jemalloc/internal/malloc_io.h', needed by `src/jemalloc.pic.o'.  Stop.

**Comment by interwq** [comment] 2017-04-07 17:13
Hi, ```malloc_io.h``` is part of dev branch instead of master. Please try ```make clean``` after you switch branch. Or if the tree is not clean for some reason, try a fresh clone and checkout master branch again.

Closing assuming not a bug. Please feel free to let us know if you still have trouble.

**Closed by interwq** 2017-04-07 17:13 UTC
