### ISSUE TITLE
Jemalloc 5.1 using (leaking?) much more memory than 4.4

### ISSUE THREAD

**Issue by santagada** [jemalloc/jemalloc#1335] opened 2018-10-04 14:18 UTC
Hi

We have been using jemalloc on a set of our internal processes that run on windows, one such of these processes creates 2x number of cores threads and converts data between two formats, those conversions do allocated a fair amount of memory (with 12 cores it goes from 2.5gb all the way to 20-30gb depending on content). We have been using Jemalloc 4.4 to replace both the windows allocator and a heavily modified version of dlmalloc.

Switching from jemalloc 4.4 to 5.1 causes the application to be using huge amounts of memory and looks to be leaking (maybe fragmenting memory)

on 4.4 I use "purge:decay,decay_time:30" and on 5.1 I tried both without any config or with "dirty_decay_ms:30"

Different behaviours:

4.4: stats.resident and "private working set" on windows match with a difference of ~300mb
5.1: stats.resident is showing 2.5GB of ram and private working set it at 8GB and it seems to starts at mostly the same but private working set on windows just grows.

**Comment by santagada** [comment] 2018-10-16 15:52
If any stats are necessary I can provide them

**Comment by interwq** [comment] 2018-10-16 20:49
Hi, thanks for reporting the issue. We don't have much windows coverage beyond the Travis CI, so it's possible some perf regression slipped into 5.1.

Yes malloc_stats would be a good start, ideally from both 4.4 and 5.1, under similar workloads and amount of time.

**Comment by santagada** [comment] 2018-10-29 18:40
maybe #1347 is related as well.

**Comment by santagada** [comment] 2018-10-30 20:33
I discovered it is not apparently leaking nonstop, but it does grow much much bigger, as you can see from the logs I'm attaching, one is running with jemalloc 4.4 the other with 5.1
[log.zip](https://github.com/jemalloc/jemalloc/files/2531532/log.zip)

**Comment by interwq** [comment] 2018-10-30 20:58
@santagada : The stats indicate only arena 0-41 are used, so I'd assume no thread created / terminated dynamically?

**Comment by santagada** [comment] 2018-10-30 22:06
We don't create threads after program start usually. This was on my machine, 16 cores, probably ~30 threads.

**Comment by interwq** [comment] 2018-10-30 22:08
Okay I'll look into #1347 first. Will come back to here afterwards.

**Comment by santagada** [comment] 2018-10-31 16:16
Found some more data points: we allocate all memory 16 bytes aligned, if I change it to be unaligned the memory load is lower, comparable to jemalloc 4.4, with the exception that it is much slower than 4.4 both aligned and unaligned. For this application jemalloc 4.4 takes 35 seconds and 5.1 uses 40 seconds.

**Comment by santagada** [comment] 2018-10-31 16:20
in one step of our process we compress a hash using lz4. that shouldn't allocated much memory, but somehow with jemalloc 4.4 it takes 899.44 ms, with 5.1 takes 3253.14 ms.

I don't fully understands this regressions, and for us the aligned allocs using much more memory is a bit unacceptable. Should I open one bug report for the memory and other for the speed regression?

**Comment by santagada** [comment] 2018-10-31 16:59
This lz4 compress allocate one uncompressed buffer for all the data, and then one buffer for the compressed data (I think it is same size as the first one). Both of them are more than 4mb. I think it weird that two lets say xMB allocations take almost 4 times longer on jemalloc 5.1

**Comment by interwq** [comment] 2018-11-02 19:30
It seems #1347 isn't related (not on Windows).

@santagada: do you mean w/o the 16B alignment, the memory usage is similar to 4.4 and doesn't grow? Let's keep the discussion in thread for now.

Is it easy for me to get a repro somehow? Even if only for the lz4 part.

**Comment by interwq** [comment] 2018-11-02 19:33
For the slow down on the lz4, it's unlikely that the cost from the two allocations takes multiple seconds, but maybe the difference in memory layout affected TLB or cache somehow. Since this part sounds more contained, can you please get the stats for both before and after the compression? You may need to call `mallctl("epoch" ...)` to force the stats refresh.

**Comment by interwq** [comment] 2018-11-02 19:36
One more thing, can you please check if with jemalloc 4 and 5, the alignment of the large buffers for lz4? IIRC, on jemalloc 4, it's likely to get 2MB aligned buffers while not so much with jemalloc 5.

**Comment by interwq** [comment] 2018-11-02 20:03
Okay more things: can you please check if the `mapped` in 5.1 stats match the private working set from Windows? Also if you could grab the stats with the current dev version, that would be helpful too since we added some detailed counters.

Again, thanks a lot for sharing the data and helping with the debugging @santagada!

**Comment by santagada** [comment] 2018-11-05 23:16
IIRC they match with windows stats. I can try to use the dev version  and check the other stuff, but I'm quite deep into implementing the stack walking for jemalloc 4.4.

So the result was that you didn't learn anything new from the stats I posted?

**Comment by interwq** [comment] 2018-11-08 22:38
Unfortunately nothing conclusive. I have some theories: 1) purging failed somehow, resulting in all unused memory stay mapped; however I couldn't find much difference on the purge path. The VirtualAlloc / VirtualFree usage looks the same for both jemalloc 4 & 5. and 2) the extent based VM management caused very bad fragmentation; however the # of bytes from fragmentation is a small fraction compared to the mapped stats.

Having the stats with the current dev branch will help us to understand what extents are taking the mapped space.

Is there any way I can repro this locally? Even for a small part of the program, like the lz4 compression?

**Comment by interwq** [comment] 2019-08-12 21:20
This should be fixed by the 5.2.1 release https://github.com/jemalloc/jemalloc/releases/tag/5.2.1

**Closed by interwq** 2019-08-12 21:20 UTC
