### ISSUE TITLE
warning "undefined behavior" in MALLOCX_ALIGN 

### ISSUE THREAD

**Issue by nicolaichuk** [jemalloc/jemalloc#354] opened 2016-03-10 15:58 UTC
in file jemalloc.h
```
#    define MALLOCX_ALIGN(a)						\
       ((int)(((a) < (size_t)INT_MAX) ? ffs((int)(a))-1 :		\
       ffs((int)((a)>>32))+31))
```

warning:

'>>': shift count negative or too big, undefined behavior

**Comment by jasone** [comment] 2016-03-11 17:37
We need yet more casts in order to make this macro do the right thing with integer constants.  The root cause is likely that you're passing an integer rather than ```size_t``` to the macro.  Until the fix is in place you can work around the issue by changing e.g. ```MALLOCX_ALIGN(64)``` to ```MALLOCX_ALIGN((size_t)64)```.

**Closed** 2016-03-11 18:13 UTC
Labels: portability
