### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#424] opened 2016-07-07 22:57 UTC
- [x] Setup Travis-CI

I don't remember the exact process when you do it from scratch, but it goes along something like:
- Signin on https://travis-ci.org with your github account
- Flick the repository switch on
- Check the settings for the repository. You may want to flick "Build only if .travis.yml is present (iirc it's off by default)
- Push something on a branch that contains the .travis.yml file.
 
- [x] Setup AppVeyor

Same as above, mostly, iirc.
- Signin on https://www.appveyor.com/ with your github account
- Create a new project, select the github repository
- In the settings, set "Custom configuration .yml file name" to ".appveyor.yml".
- Push something on a branch that contains the .appveyor.yml file.

**Comment by jasone** [comment] 2016-07-08 00:58
Thank you.  I've performed all the above steps and kicked off a manual AppVeyor build; Travis CI apparently can't be manually triggered.  I'll leave this issue open until it's clear that everything is working as intended.

**Comment by glandium** [comment] 2016-07-08 01:11
In case you don't know, the CI status is displayed on the "branches" page (small dot icon in the middle):
https://github.com/jemalloc/jemalloc/branches

**Comment by glandium** [comment] 2016-07-08 04:40
And a Travis-CI build fired up for the PR I pushed just now.
It might be worth cherry-picking 91278fbddfb5a0adf265b1b9907a1509b4e1e18c and 2ea7742e6ffa7fb20538c0e2dba6ceec80cbe8d9 on master too.

**Comment by jasone** [comment] 2016-07-08 06:10
Milestone set to make sure the CI config files are cherry-picked.

**Comment by jasone** [comment] 2016-09-26 22:50
CI config files cherry-picked as 43d4d7c37376e2ac5faf9c0adf30647d7c288106 and 3bb044c80766e1cbe14e246ec2232650859a0dc9.

**Comment by jasone** [comment] 2016-09-26 22:52
CI config files cherry-picked into rel-4.3.0 (which will be merged into master during 4.3.0 release) as 43d4d7c37376e2ac5faf9c0adf30647d7c288106 and 3bb044c80766e1cbe14e246ec2232650859a0dc9.

**Closed** 2016-09-26 22:52 UTC
Labels: testing

**Comment by jasone** [comment] 2016-10-29 07:54
As of 1dcd0aa07fa16d2f70494baf997ac85b41de2ef1 (dev) and e46f8f97bc4dc3298e1d3b452ee69616fdbcd43e (rel-4.3.0), all CI tests pass.

**Comment by glandium** [comment] 2016-10-29 09:09
I'll have to actually test but I wouldn't be surprised if those last changes break building Firefox with jemalloc 4.3.
