### ISSUE TITLE
Jemalloc exhibits a huge amount of mapped memory

### ISSUE THREAD

**Issue by yuslepukhin** [jemalloc/jemalloc#508] opened 2016-11-21 22:49 UTC
See attached image that shows that Jemalloc has mapped a huge amount of memory.
The side effect of it is that metadata consumes a lot of committed memory. 

The version we are running is 4.2.1 with 3 fixes on top of it.

b54d160dc4507eab5fb64e2e293019c5d3afd18c (Do not (recursively) allocate within tsd_fetch())
e5effef428b5bf941e1697f6000c97f1ce734756  (use spinning)
577d4572b0821a15e5370f9bf566d884b7cf707c (Make dss operations lockless)

**Comment by yuslepukhin** [comment] 2016-11-21 22:49
![jememorycounter for share](https://cloud.githubusercontent.com/assets/11303988/20503912/b5880f6c-aff9-11e6-8153-780dd0108887.png)
![jememorycounter for share 1](https://cloud.githubusercontent.com/assets/11303988/20503913/b59c8906-aff9-11e6-8f99-ad0c80c20b13.png)

**Comment by yuslepukhin** [comment] 2016-11-21 22:52
![jememorycounter for share](https://cloud.githubusercontent.com/assets/11303988/20503996/1519484c-affa-11e6-891b-53f6e61550ea.png)
![jememorycounter for share 1](https://cloud.githubusercontent.com/assets/11303988/20503995/151451e8-affa-11e6-847f-0d091bf2f9d6.png)

**Comment by jasone** [comment] 2016-11-21 22:57
I fixed some serious virtual memory issues in 4.3.[01], one of which was Windows-specific.  Does this issue reproduce for 4.3.1?

**Comment by jasone** [comment] 2016-11-21 23:04
See #487.

**Comment by yuslepukhin** [comment] 2016-11-21 23:06
@jasone Thanks, will check this out

**Comment by yuslepukhin** [comment] 2016-11-28 18:00
4.3.1 fixes the issue. I will verify if 4.2.1 with rolled fixes has the same effect..
On a general note, we have been struggling to find a good quality stable release.
IMHO, I have been chasing a tail because many fixes introduce other issues.
At the same time fixes do not include  regression tests.
I agree that the community may have done more to contribute to unit tests.

**Comment by jasone** [comment] 2016-11-28 20:04
Re: testing and stability, I have also been frustrated and dismayed by stability and performance of the 4.x releases, which is why I've recently put a bunch of effort into resolving all the Windows-specific issues and making continuous integration testing part of the normal development workflow.  I think we're rapidly converging on a solid 4.x release (4.3.1 seems pretty good so far).  Re: more tests, I agree that we still need more comprehensive testing, but I want to avoid overly brittle tests that rely too heavily on internal behaviors.  My general plans include more load/stress testing, which should help detect performance regressions that don't obviously manifest as correctness issues.

**Comment by jasone** [comment] 2016-11-28 20:04
Marking as duplicate of #487.

**Comment by jasone** [comment] 2016-11-28 20:09
Re: Windows support, it's worth mentioning that the _only_ thing I use Windows for is jemalloc testing.  I would have much preferred to leave Windows to developers who use it, but no one besides me even made efforts to address compiler warnings until very recently.  I hope that with the higher quality we've recently achieved for Windows, people will increasingly report and/or fix problems to help keep it in good shape.

**Closed by jasone** 2016-11-28 20:09 UTC
Labels: duplicate
