### ISSUE TITLE
Test suite failure on multiple architectures with --enable-prof

### ISSUE THREAD

**Issue by paravoid** [jemalloc/jemalloc#338] opened 2016-02-23 19:54 UTC
Hi,

On Debian, --enable-prof was [briefly enabled](https://bugs.debian.org/767342) but it was [quickly reverted](https://bugs.debian.org/807548) as it resulted into test build failures [across multiple architectures](https://buildd.debian.org/status/logs.php?pkg=jemalloc&ver=3.6.0-4) (32-bit but also 64-bit, e.g. arm64). This was with 3.6.0, but I've reproduced this just now on an arm64 host with 4.0.4.

The failure is this:
```
=== test/unit/prof_accum ===
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 5 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 6 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 5 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 5 > 1: Expected larger backtrace count increase
thd_start:test/unit/prof_accum.c:52: Failed assertion: (bt_count_prev+(i-i_prev)) <= (bt_count) --> 5 > 1: Expected larger backtrace count increase
test_idump: fail
--- pass: 0/1, skip: 0/1, fail: 1/1 ---
```

This was with:
```
(sid_arm64-dchroot)paravoid@asachi:~/jemalloc-4.0.4$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/5/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 5.3.1-9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-arm64 --with-arch-directory=aarch64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --enable-fix-cortex-a53-843419 --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 5.3.1 20160220 (Debian 5.3.1-9) 
```

Debugging this is over my head, but I'd be happy to test potential fixes on arm64 or other architectures (using Debian's porterbox network).

**Comment by jasone** [comment] 2016-02-24 03:11
This looks like a side effect of enabling global link-time optimization, which can allow elimination of recursion that this test specifically relies on.  You can either change the linker flags for the tests, or you can disable the test.

Closing since this is a package building artifact rather than specifically an issue with jemalloc.  If you find that a build system patch is useful (e.g. to allow passing separate linker flags for tests), I'm open to a patch.

**Comment by paravoid** [comment] 2016-02-24 12:41
Thanks for the quick response. It's not really a package building artifact, though.

On the same arm64 box, running "./configure --enable-prof; make; make check" on a freshly extracted jemalloc 4.0.4 tarball, with no C/CPP/LDFLAGS defined in the environment at all, results in the same test suite failure.

**Comment by jasone** [comment] 2016-02-24 16:51
Okay, unless this is a general issue with new toolchain versions I haven't tested yet, it seems very likely that the issue is related to the way in which the toolchain is configured (i.e. default compilation flags).  I've not encountered this issue at all since I split the mutually recursive functions in the test into separate compilation units, despite testing on numerous platforms.

**Comment by paravoid** [comment] 2016-02-24 18:05
This is the default config on this arm64 box running Debian unstable (and gcc version 5.3.1 20160220 (Debian 5.3.1-9)):
```
CONFIG             : 
CC                 : gcc
CFLAGS             : -std=gnu99 -Wall -Werror=declaration-after-statement -pipe -g3 -fvisibility=hidden -O3 -funroll-loops
CPPFLAGS           :  -D_GNU_SOURCE -D_REENTRANT
LDFLAGS            : 
EXTRA_LDFLAGS      : 
LIBS               :  -lpthread
TESTLIBS           : 
RPATH_EXTRA        : 
```

**Comment by paravoid** [comment] 2016-02-26 11:31
Should this bug be reopened then? Anything else I could do to help you debug this? Happy to test patches across a number of diverse architectures, for example.

**Comment by jasone** [comment] 2016-02-26 16:28
Can you please try configuring with ```--enable-debug``` to verify that compiler optimization is responsible for flattening the call chain?  I'd expect ```-flto``` to be necessary in the compiler flags, but perhaps ```-O3``` implies ```-flto```.  Another thing to try is adding ```EXTRA_CFLAGS=-fno-lto``` to the configure command, e.g.

  ```EXTRA_CFLAGS=-fno-lto ./configure```

If LTO is indeed responsible for this, we'll either need to modify the build system for the two source files in question (```test/src/btalloc_[01].c```), figure out a way to thwart the optimization, or just remove the test.

**Comment by paravoid** [comment] 2016-02-26 17:41
Building with `./configure --enable-prof --enable-debug; make; make check` resulted in 
```
CONFIG             : --enable-prof --enable-debug
CC                 : gcc
CFLAGS             : -std=gnu99 -Wall -Werror=declaration-after-statement -pipe -g3 -fvisibility=hidden
CPPFLAGS           :  -D_GNU_SOURCE -D_REENTRANT 
LDFLAGS            : 
EXTRA_LDFLAGS      :  
LIBS               :  -lgcc -lm -lpthread
TESTLIBS           : 
RPATH_EXTRA        :  
```
…but a failure nevertheless.

Note that the Debian builds (repotred previously as failing) were with `-O2` (Debian's default):
```
CC                 : gcc
CPPFLAGS           : -D_FORTIFY_SOURCE=2  -D_GNU_SOURCE -D_REENTRANT
CFLAGS             : -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=gnu99 -fvisibility=hidden
LDFLAGS            : -Wl,-z,relro
EXTRA_LDFLAGS      : 
LIBS               :  -lgcc -lm -lpthread
RPATH_EXTRA        : 
```

I also tried with your suggestion `EXTRA_CFLAGS=-fno-lto ./configure --enable-prof`:
```
CONFIG             : --enable-prof
CC                 : gcc
CFLAGS             : -std=gnu99 -Wall -Werror=declaration-after-statement -pipe -g3 -fno-lto -fvisibility=hidden -O3 -funroll-loops
CPPFLAGS           :  -D_GNU_SOURCE -D_REENTRANT
LDFLAGS            :
EXTRA_LDFLAGS      :
LIBS               :  -lgcc -lm -lpthread
TESTLIBS           :
RPATH_EXTRA        :
```
…and, unfortunately, this failed as well, exact same error.

**Comment by paravoid** [comment] 2016-03-22 23:36
I don't mean to be a pest, but is there anything else I could do to help you debug this?

**Comment by petevine** [comment] 2016-03-23 11:52
I can reproduce on ARM, even with `-O0`, but it doesn't seem to cause any problems outside of the failing test.

**Comment by jasone** [comment] 2016-03-23 20:29
@paravoid, I think this is simply a case of the compiler being clever enough to undermine the test, but I can't devise a solution until I have an environment in which to reproduce the failure.  None of my 5+ test environments reproduce the failure, so I'm planning to set up a new Debian and/or Ubuntu VM as a first step in resolving this issue.

**Comment by paravoid** [comment] 2016-04-07 20:34
@jasone, if those VMs are going to be x86, you'd probably be as equally unable to reproduce, since this issue typically manifests only on non-i386/non-amd64.

While we could [set you up with an account to access the Debian porterbox](https://dsa.debian.org/doc/guest-account/) network and all of its architectures, that would require some effort on your side for the application and some time for the request to be processed.

Instead, I thought it'd be easier and faster for me to rent an armhf server from [Scaleway](https://www.scaleway.com/) and add your SSH keys (at least [the ones you have configured for GitHub)](https://github.com/jasone.keys) there so that you can just SSH and debug. I set it up with Debian, upgraded it to Debian unstable, installed git and the rest of the build environment and jemalloc's build-dependencies, as well checked out jemalloc's latest master (4.1.0-32-g2ee2f1e right now) and verified that the failure is reproducible there.

You can SSH into it by `ssh root@163.172.140.186` and debug. The tree is under `~/jemalloc` and is already `autoreconf`ed, `./configure`d with `--enable-prof --enable-debug` and made/made checked (which fails on `test/unit/prof_accum`, as above). 

This is a system I've rented exclusively for you to debug this issue, so you get root and you can modify it/play with it as much as you'd like — no need to ask. Just let me know once you're done needing it, so that I can destroy it and stop paying for it :)

**Comment by jasone** [comment] 2016-04-10 17:51
Thanks @paravoid, I'll try to dig into this on the VM you set up Monday or Tuesday, depending on how quickly my other Monday tasks go.

**Comment by jasone** [comment] 2016-04-12 19:49
This appears to be due to a bug in ```_Unwind_Backtrace()```, which is part of libgcc.  I added code to verify that the callback jemalloc passes in is never called.  Additionally, ```_Unwind_Backtrace()``` returns ```_URC_FAILURE```, which is generic, "unspecified failure of some kind" according to the header it is defined in.  It appears that one of the two problems reported in [this LLVM bug report](https://llvm.org/bugs/show_bug.cgi?id=21053) corresponds almost exactly to the issue we're seeing.

Unfortunately, libunwind does not seem to be available via ```apt-get``` on the machine you set up, presumably because it hasn't been ported, so there are no good alternatives at the moment.

I'm going to label this as "notabug" and remove the milestone.  It probably doesn't make sense to leave this issue open, but I'll wait for feedback before making that decision.

**Comment by jasone** [comment] 2016-04-12 19:53
BTW, I found and fixed bab58ef401b0dec8230bd2d371e135009cd06924 while investigating (clang warned).

**Comment by paravoid** [comment] 2016-04-13 13:34
Thanks for the investigation @jasone :)

First of all, libunwind is available on ARM ports — you probably could not find it because the packages are named by Debian conventions: `libunwind8` (after its SONAME, to allow for coinstabillity of multiple ABIs, e.g. during a transition) and `libunwind-dev` for its development headers.

I installed it now and built the same revision with `--enable-prof --enable-prof-libunwind` and it did, indeed, built and ran the test suite successfully. Progress!

That said, the test suite had failed before with that error on 13 different official and unofficial Debian ports (_arm64, armel, armhf, hppa, hurd-i386, mips, mips64el, mipsel, powerpc, ppc64, ppc64el, sh4, sparc64_). If this is a libgcc bug it's not one that's very architecture-specific :/ libunwind is available on many of those architectures (_arm64, armel, armhf, mips, mips64el, mipsel, powerpc, ppc64el_), but not all of them, and it typically lags behind when new ports are created, since its code paths are obviously architecture-specific. So I'm still looking for a better/more portable/future-proof solution.

Pardon my ignorance, but does this libgcc bug present an actual problem with the library to the end-user or is this just a test suite artifact, as theorized above before your investigation?

Do you think there is a way to `--enable-prof` in a way that would not require libunwind but also would not fail due to that libgcc bug (perhaps e.g. disable the test if it's not indicative of a wider issue)? I would nevertheless build with libunwind where available as this sounds like a better solution overall, but I'd prefer it if we were not tightly coupled with libunwind and its architecture set.

**Comment by jasone** [comment] 2016-04-13 16:05
The test failure is real, so any attempt to use heap profiling with the non-functional ```_Unwind_Backtrace()``` will fail to generate backtraces, and the heap profiles will be empty.  It won't really hurt anything to build jemalloc this way, other than that supposedly available functionality won't work.

In general my experience with libunwind-based backtracing has been better than with libgcc-based backtracing, so in my opinion libunwind is a worthwhile dependency when enabling heap profiling.

**Closed** 2016-05-03 16:45 UTC
Labels: notabug, portability
