### ISSUE TITLE
Possible performance regression since 23694b0.

### ISSUE THREAD

**Issue by ldalessa** [jemalloc/jemalloc#230] opened 2015-05-07 20:12 UTC
In [HPX](https://hpx.crest.iu.edu) we make extensive use to manage a number of different address spaces for various kinds of registered memory accesses. Prior to support for explicit caches, we would link two or three instances of libjemalloc with different prefixes, so that we could use caching without having allocations from different address spaces collide in the cache. We have been using 23694b07457f3aaf9605a4ff6b386f3c897eb624 for some time now with good performance results.

I recently pulled HEAD, (8a03cf039cd06f9fa6972711195055d865673966 as of this writing), and updated our code to use the custom cache capabilities. First of all, this functionality is *wonderful* for us. It has allowed me to simplify a messy allocation infrastructure into something quite a lot more pleasant. We only have to link one libjemalloc(!) and we'll be able to use 4.0 unmodified once it becomes available as long as mallocx is exported.

I have noticed a performance regression between the two versions though. Part of our system is a user-level-thread scheduler, and one of the SMP torture tests we use is a naive fibonacci that expands the computation tree using threads. This really taxes the allocator—basically it's an allocation stress test. It doesn't use any of the custom allocation infrastructure because we're not including network support in this test.

If you download [HPX](https://hpx.crest.iu.edu) and configure/make, you'll get the test in examples/fibonacci, just run it as `fibonnaci --hpx-threads=[threads] n` or use `numactl` to control thread affinity. It should build on x86_64-linux or darwin without any issues. When we preload 23694b07457f3aaf9605a4ff6b386f3c897eb624 vs HEAD, and set MALLOC_CONF="lg_chunk:22", we see that HEAD results in 1.5-2x longer runtimes for the same fibonacci number/scheduler thread count. 

We're running almost exclusively on NUMA nodes.

```bash
$ numactl --hardware
available: 2 nodes (0-1)
node 0 cpus: 0 2 4 6 8 10 12 14
node 0 size: 16338 MB
node 0 free: 13125 MB
node 1 cpus: 1 3 5 7 9 11 13 15
node 1 size: 16384 MB
node 1 free: 14578 MB
node distances:
node   0   1 
  0:  10  20 
  1:  20  10 
$ head /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
stepping	: 7
microcode	: 0x70d
cpu MHz		: 2599.875
cache size	: 20480 KB
physical id	: 0
```

It's a bit worse on NUMA Haswell systems. I see that there has been *a lot* of great feature and configuration expansion between the two versions. Is there an obvious configuration parameter that would help us here, or is there a real performance regression that needs to be dealt with? The lg_chunk control is vital, with 2^18 it's like 10x slower.

**Comment by ldalessa** [comment] 2015-05-07 21:05
For what it's worth, I did some spot testing with `numactl` and that's really not and issue, still 1.5x to 2x runtime in HEAD. Also, this is not a blocker for us, this kind of allocator pressure is not something we see that much in real applications—or at least we have other issues that are a bigger problem. I'm just trying to make sure that there isn't something obvious configuration-wise that I should be doing.

**Comment by mckellyln** [comment] 2015-05-08 13:36
I have noticed a significant slowdown in jemalloc performance since a few revs ago as well.  I did not record what the specific version was before that I used, sorry,  but the latest version is at least 2x+ slower in our tests, both single and many threads.  Nothing I can find in the test code has changed which made me think it was something in jemalloc but I have not instrumented/profiled to find out any more info.

**Comment by ldalessa** [comment] 2015-05-08 18:11
I think that I resolved the issue. Part of our test performs relatively high frequency allocations of 32kb objects (lightweight stacks). I implemented simple freelisting for these—something that's been on my list of things to do for a while, and the jemalloc performance degradation is gone.

Obviously, freelisting is agnostic to the underlying allocator version—reducing dallocx instances is good either way, however I suspect that something changed with respect to allocation of larger objects that makes them much slower, but I don't know enough about the internals to know what. In any case, we're back to our previous performance.

It would still be nice to know if there is a parameter that would have effected the same change.

**Comment by jasone** [comment] 2015-05-08 18:19
I'd really appreciate it if you can bisect the slowdown.  If it's due to search overhead introduced by 97c04a93838c4001688fe31bf018972b4696efe2 I want to do something about it before releasing 4.0.0.  On the other hand, if it's due to fragmentation reduction increasing the frequency with which run coalescing succeeds, that's a victory of sorts.

**Comment by mckellyln** [comment] 2015-05-08 19:10
ok, I will try to reproduce, and thank you for jemalloc work.
with 3.6.0 -
./mtestje  12.63s user 1.01s system 87% cpu 15.629 total
I will try to find my previous jemalloc version that I thought was faster than this.
Ubuntu 12.04 kernel 3.13.0-52
profile with jemalloc 3.6.0 -
+  19.99%  mtestje  libjemalloc.so.1    [.] arena_avail_tree_insert
+  14.00%  mtestje  libjemalloc.so.1    [.] arena_avail_tree_remove
+  12.50%  mtestje  libjemalloc.so.1    [.] arena_chunk_dirty_insert
+  11.82%  mtestje  libjemalloc.so.1    [.] arena_chunk_dirty_remove
+   6.69%  mtestje  libjemalloc.so.1    [.] arena_purge
+   4.58%  mtestje  libjemalloc.so.1    [.] je_arena_malloc_large
+   4.24%   python  python2.7           [.] 0x000000000014f936
+   2.59%   python  python2.7           [.] PyEval_EvalFrameEx
+   1.96%  mtestje  libjemalloc.so.1    [.] free
+   1.16%  mtestje  libjemalloc.so.1    [.] arena_run_dalloc

**Comment by ldalessa** [comment] 2015-05-08 21:25
Sure, I can try and bisect. There is definitely a policy boundary triggering the behavior we see.

```bash
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:22" ./examples/fibonacci 37 --hpx-stacksize=4096
fib(37)=24157817
seconds: 4.5608462
localities: 1
threads/locality: 16
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:22" ./examples/fibonacci 37 --hpx-stacksize=8192
fib(37)=24157817
seconds: 4.5988855
localities: 1
threads/locality: 16
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:22" ./examples/fibonacci 37 --hpx-stacksize=12288
fib(37)=24157817
seconds: 4.6086338
localities: 1
threads/locality: 16
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:22" ./examples/fibonacci 37 --hpx-stacksize=16384
fib(37)=24157817
seconds: 6.4558239
localities: 1
threads/locality: 16
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:22" ./examples/fibonacci 37 --hpx-stacksize=32768
fib(37)=24157817
seconds: 6.4906859
localities: 1
threads/locality: 16
```

You can see the runtime go from 4.5 seconds to 6.5 seconds when I cross between 12k and 16k stacks. The default chunk size is really bad for us, of course. The boundary then seems to show up between 4k and 8k stacks.

```bash
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:18" ./examples/fibonacci 37 --hpx-stacksize=4096
fib(37)=24157817
seconds: 4.5506283
localities: 1
threads/locality: 16
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:18" ./examples/fibonacci 37 --hpx-stacksize=8192 
fib(37)=24157817
seconds: 9.8178719
localities: 1
threads/locality: 16
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:18" ./examples/fibonacci 37 --hpx-stacksize=32768
fib(37)=24157817
seconds: 68.8298394
localities: 1
threads/locality: 16
```

I'll post once I've bisected. Thanks, Luke

**Comment by ldalessa** [comment] 2015-05-08 21:31
Okay, quick note, that commit does have an impact, but it's parent wasn't doing all that well either (these are both with just `./autogen.sh` builds).

```bash
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc_5707d6f.so.2 MALLOC_CONF="lg_chunk:22" ./examples/fibonacci 37       
fib(37)=24157817
seconds: 8.0505219
localities: 1
threads/locality: 16
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc_97c04a9.so.2 MALLOC_CONF="lg_chunk:22" ./examples/fibonacci 37
fib(37)=24157817
seconds: 9.1205069
localities: 1
threads/locality: 16
```

I'll go back in time a bit later tonight and see where things started to go wrong for our use case.

**Comment by ldalessa** [comment] 2015-05-10 14:19
Okay, performance bisection doesn't work all that well so I just ran all of the revs. Right around the introduction of tcaches it doesn't terminate, and there are a couple of outliers, but there has been a general increase in time for us.

The following chart is the average of seven runs at each revision with the command `LD_PRELOAD=libjemalloc_HASH.so.2 MALLOC_CONF="lg_chunk:22" timeout 300s ./examples/fibonacci 37`. This spawns the naive recursive fibonacci computation using user-level threads with 32k stacks.

The libraries were all build as `./autogen.sh --disable-valgrind --disable-stats --disable-fill --with-install-suffix=_HASH`. Fibonacci was built with `CFLAGS=-O3` but not `-flto`.

Everything was built with `gcc-4.9.2`.

The system is the same one as above.

```bash
$ numactl --hardware
available: 2 nodes (0-1)
node 0 cpus: 0 2 4 6 8 10 12 14
node 0 size: 16338 MB
node 0 free: 13125 MB
node 1 cpus: 1 3 5 7 9 11 13 15
node 1 size: 16384 MB
node 1 free: 14578 MB
node distances:
node   0   1 
  0:  10  20 
  1:  20  10 
$ head /proc/cpuinfo 
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
stepping    : 7
microcode   : 0x70d
cpu MHz     : 2599.875
cache size  : 20480 KB
physical id : 0
```

![Time for each revision](http://www.luked.net/fib_perf.png)

You can get the pdf, which is easier to read, [here](http://www.luked.net/fib_perf.pdf). I can also send out the raw data if it matters.

**Comment by glandium** [comment] 2015-05-13 23:14
Since I've been tracking some regressions of my own, I thought your testcase was interesting, so I ran it on a i7-870 (only one run, though, but that's good enough for a trend), with jemalloc 2.0, 3.0 and every revision that builds and doesn't take more than 300s since 3.0. The result is that there have been many different regressions since 3.0:
https://docs.google.com/spreadsheets/d/1sW8momIPE_-46uGw8c4YN2ngswHhL3_IycoIdjWWQ7M/pubchart?oid=1097650653&format=interactive
I'll try to do the same with the workload I do care about (some Firefox benchmarks)

**Comment by glandium** [comment] 2015-05-13 23:20
https://docs.google.com/spreadsheets/d/1sW8momIPE_-46uGw8c4YN2ngswHhL3_IycoIdjWWQ7M/edit?usp=sharing For the full spreadsheet (and probably a better graph because it's fullscreened)

**Comment by ldalessa** [comment] 2015-05-14 01:27
Oh, the rollover effect on the google-docs spreadsheet is nice. I'll have to try using that the next time I need to share data. Trend looks basically the same, which is nice verification of what we see when we don't freelist 32kb allocations.

**Comment by jasone** [comment] 2015-05-19 00:49
It's apparent that the revision region of poor performance in the chart posted by @glandium is due to aggressive dirty page purging in applications that have minimal memory usage (resolved by 6505733012458d8fcd0ae8e1f1acdc9ffe33ff35).  Since the first remaining regression was likely in that region, I conducted a similar experiment, but with [dirty page purging disabled](https://docs.google.com/spreadsheets/d/1c7xxmOlUMNNcGkgP3oGhO_JOxeIsfN4QRCcJnRrk4bI/edit?usp=sharing).  As you can see, the results are quite different, and the trend is one of progression rather than regression.  Arena caches (#148) will probably add some hysteresis and smooth out performance, but meanwhile I don't think there's anything fundamentally concerning here.

**Comment by glandium** [comment] 2015-05-19 01:07
There still is a big difference between current tip and 3.0 on my data, though.

**Comment by jasone** [comment] 2015-05-19 07:30
I did another run with dirty page purging enabled (see [sheet 4](https://docs.google.com/spreadsheets/d/1c7xxmOlUMNNcGkgP3oGhO_JOxeIsfN4QRCcJnRrk4bI/edit?usp=sharing)), and my results aren't radically different than with dirty page purging disabled.  I did all the runs in a VMware guest (host is OS X, i7-4980HQ) running Ubuntu 14.04.2 (3.13.0-52-generic kernel).

@glandium and @ldalessa, my results are significantly different than yours, yet I'm quite certain that other than statistical noise they're reproducible on my machine.  What operating systems are you using?

**Comment by glandium** [comment] 2015-05-19 10:15
Linux 3.16 on a downclocked i7 870. Note your graph starts after 3.6, which covers the originally reported range, but not mine. Also note that I was getting data with the same setup as the original report, so using lg_chunk:22. Also note that the huge regression spike on my graph started when class sizes changed, and while kind of resolved by 6505733, on my machine, 6505733 was still slower than before that regression.

**Comment by ldalessa** [comment] 2015-05-19 11:20
Hi Jason, thanks for looking into this for us. We have an older Ubuntu distribution.

```bash
$ uname -a
Linux [cut] 3.2.0-59-generic #90-Ubuntu SMP Tue Jan 7 22:43:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

I see that you are only using 4 threads. glandium is possibly using hyperthreading, which could account for a difference. The system I tested has HT disabled in the bios. We don't do anything special with respect to affinity---we expect `numactl` or more typically `mpirun/aprun` to control the process affinity map to prevent HT use. You could `numactl` to set the affinity specifically to the right place to see if that changes anything, or use all 8 HT.

I should note that we find basically the same 2 steps between 97c049a and HEAD on all of the flavors of Linux that we run on. We're also seeing some regressions on other applications that do larger  (20k-ish) allocations. Still diagnosing those---they might only happen during distributed execution which could make it more difficult for you to test, do you have MPI on your VM?

**Comment by ldalessa** [comment] 2015-05-19 13:58
Oh, one thing to be careful of here. I added stack freelisting in [HPX 19e6615](https://gitlab.crest.iu.edu/extreme/hpx/commit/19e6615a212de88b1cea5e541c469c15e4bc67f6), so if you pulled a version more recent than that, you wouldn't see the issue.

You can disable the freelist with '--hpx-sched-stackcachelimit=0', which will expose the issue.

```bash
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:22" ./examples/fibonacci 37       
fib(37)=24157817
seconds: 3.5789191
localities: 1
threads/locality: 16
$ LD_PRELOAD=~/jemalloc/lib/libjemalloc.so.2 MALLOC_CONF="lg_chunk:22" ./examples/fibonacci 37 --hpx-sched-stackcachelimit=0
fib(37)=24157817
seconds: 9.9896856
localities: 1
threads/locality: 16
```

**Comment by jasone** [comment] 2015-05-19 15:36
Ah, I ran all my experiments with [HPX b99621bf38f570e8c850ca918a31e7058a99d40e](https://gitlab.crest.iu.edu/extreme/hpx/commit/b99621bf38f570e8c850ca918a31e7058a99d40e), which does have the freelisting.  Can I simply revert the freelisting commit and reproduce the issue with the version I pulled, or should I check out an older version?

**Comment by ldalessa** [comment] 2015-05-19 16:06
You can either just use [the 1.0 distribution](http://hpx.crest.iu.edu/download) or you can use the `--hpx-sched-stackcachelimit=0` runtime flag with the development version as above (that will disable the freelisting, -1 means no bound to the freelist, while some integer `n` will cap the number of freelisted stacks). I am constantly breaking things in git, so I don't think reverting freelisting will be fruitful, sorry.

I would say just use 1.0---nothing important has changed for fibonacci (except for freelisting :-).

**Comment by jasone** [comment] 2015-05-19 21:19
It looks like I'm getting similar results now with ```--hpx-sched-stackcachelimit=0```.  I captured jemalloc stats and was surprised to see that the number of 32 KiB allocation requests and underlying arena allocation events is identical, which means thread caching is doing no good whatsoever.  Are the thread stacks freed by their associated threads just before thread exit?  If so, then thread cache destruction during thread exit is preventing any tcache hits for 32 KiB allocations.  I'll keep running through the jemalloc revs (will probably take 5+ hours) to look for specific causes of the speed regressions, but I currently suspect all the slowdowns are related to virtual memory fragmentation reduction improvements, which results in large allocation/deallocation executing more involved code paths.

**Comment by ldalessa** [comment] 2015-05-19 22:16
Without application level (lightweight) stack caching the system thread will find a work item to process, malloc a 32kb stack to execute that work item on, do something like 1/2 a longjmp to start running on the newly allocated stack (work item + stack), free the previous stack, and then do the other 1/2 the longjmp to start running the new thread. We would normally expect that freed stack to be cached by jemalloc, and reused for the next thread create event in such a setting.

There are other patterns that also occur, that may result in a sequence of mallocs that aren't matched immediately by frees---these will have to get new allocations from the chunk because there wouldn't be any cached stacks. At some point there will be a sequence of frees unmatched immediately by mallocs---these would normally supply cached 32k objects to subsequent mallocs.

If the jemalloc cache isn't effective in this application for this size allocation, then is there a simple conf option that I would want to set to make sure that 32k allocations (or really any large allocations) *are* being cached, or retained long enough?

**Comment by jasone** [comment] 2015-05-20 00:55
I think this is fixed now.  See 5154175cf1e6e7b1a2ed0295c232e60384944b3f and 6591ff09d80e11f36603a75b32dc6a9b81fb3d47 in particular.

**Comment by ldalessa** [comment] 2015-05-20 01:05
Great! Quick spot check shows a drop from 10s to 4s (both with freelisting disabled). I suspect this is actually faster than we were seeing at https://github.com/jemalloc/jemalloc/commit/23694b07457f3aaf9605a4ff6b386f3c897eb624. This definitely seems to have cleaned up our issue.

Thank you.

**Closed** 2015-05-21 13:58 UTC
Labels: optimization
