### ISSUE TITLE
test/integration/mallocx still fails on older 32 bit

### ISSUE THREAD

**Issue by ingvarha** [jemalloc/jemalloc#448] opened 2016-08-23 11:33 UTC
As seen on the -discuss list:

test/integration/mallocx still fails on older 32 bit in trunk and 4.2.1, as it did
in 4.1.1.

Target systems failing are rhel5 and rhel6 on i686 and ppc. Newer 32 bit systems, like fedora 24, does not have this problem.

Typical test output:
=== test/integration/mallocx ===
test_overflow: pass
test_oom: pass
test_basic: pass
test_alignment_and_size:test/integration/mallocx.c:175: Failed
assertion: (ps[i]) != (NULL) --> 0x0 == 0x0: mallocx() error for
alignment=33554432, size=67108861 (0x3fffffd)
test/test.sh: line 22:  1969 Segmentation fault      (core dumped) ${t}
/builddir/build/BUILD/jemalloc-4.2.1/ /builddir/build/BUILD/jemalloc-4.2.1/
Test harness error
make: *** [check_integration] Error 1

Full build logs:

el5/ppc:
https://kojipkgs.fedoraproject.org//work/tasks/4856/15114856/build.log

el5/i386:
https://kojipkgs.fedoraproject.org//work/tasks/5786/15115786/build.log

el5/i686:
https://kojipkgs.fedoraproject.org//work/tasks/5839/15115839/build.log

el6/i686:
https://kojipkgs.fedoraproject.org//work/tasks/5730/15115730/build.log

Best regards,
Ingvar Hagelund

**Comment by jasone** [comment] 2016-09-27 16:29
I'm working on setting up a CentOS 6 i686 VMware guest today, under the assumption that it will allow me to reproduce this failure.  The Ubuntu 13.10 i686 setup I've been using for 32-bit testing passes all the tests.

**Comment by jasone** [comment] 2016-09-29 19:31
I'm seeing multiple test failures on CentOS 6.8 i686.  None of them appear to be exactly the same as reported here, but they are probably related, so I will track their fixes here.

**Comment by jasone** [comment] 2016-10-04 04:53
871a9498e13572f99451ed88db36cda6c9fecf8f and a5a8d7ae8dd638cf538cae3b340afe6d1d787954 fix size class overflow bugs on 32-bit CentOS 6, for the dev branch.  To backport the fixes to 4.3.0, we will need to cherry-pick 3aea827f5e7d07ce156476bba8a843640969de51, but I'm going to take a close look before doing so because I'm worried about replacing one set of bugs with another potentially incompletely resolved set.

**Comment by jasone** [comment] 2016-10-05 03:32
I've cherry-picked some relevant revisions from the dev branch to a branch based on rel-4.3.0 to futher explore this issue, and it is now apparent that 871a949 and a5a8d7a are not relevant to 4.x versions, because large size classes stop well short of the maximum size class, and the huge size class machinery uses different code paths.

Furthermore, I cannot reproduce the issue reported here on i686 CentOS 6.8, which would presumably be equivalent to the el6/i686 in the original failure report.  The links to the full build logs are no longer valid, so I'm not sure what to do short of installing RHEL6 and hoping it's somehow different that CentOS 6.

**Comment by jasone** [comment] 2016-10-28 18:40
I've fixed more issues related to 32-bit systems (see #393), and those ones looked similar to what is reported here.  Closing as a duplicate; please re-open if problems persist.

**Closed by jasone** 2016-10-28 18:40 UTC
Labels: duplicate, testing

**Comment by ingvarha** [comment] 2016-11-01 22:06
Thanks, Jason. With commits 2c53faf eaecaad b99c72f added, jemalloc-4.2.1 builds fine on el6/i686 el5/i686 and el5/ppc

Ingvar
