### ISSUE TITLE
jemalloc-5.1.0: Multiple tests failing on s390x on fedora rawhide (fedora-30-to-be) (gcc-9.0.1)

### ISSUE THREAD

**Issue by ingvarha** [jemalloc/jemalloc#1434] opened 2019-02-14 13:48 UTC
jemalloc-5.1.0 fails the test suite on s390x on fedora 30 (gcc-9.0.1):

BUILDSTDERR: test_gen_rand_32 (non-reentrant): fail
BUILDSTDERR: test_gen_rand_32 (libc-reentrant): fail
BUILDSTDERR: test_gen_rand_32 (arena_new-reentrant): fail
BUILDSTDERR: test_by_array_32 (non-reentrant): fail
BUILDSTDERR: test_by_array_32 (libc-reentrant): fail
BUILDSTDERR: test_by_array_32 (arena_new-reentrant): fail
BUILDSTDERR: test_gen_rand_64 (non-reentrant): fail
BUILDSTDERR: test_gen_rand_64 (libc-reentrant): fail
BUILDSTDERR: test_gen_rand_64 (arena_new-reentrant): fail
BUILDSTDERR: test_by_array_64 (non-reentrant): fail
BUILDSTDERR: test_by_array_64 (libc-reentrant): fail
BUILDSTDERR: test_by_array_64 (arena_new-reentrant): fail

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/5746/32805746/build.log

I have also tested Current release candidate 8e9a613 with the same results.

Ingvar

**Comment by sharkcz** [comment] 2019-02-14 15:00
This is probably caused by gcc9, I'm not seeing any issues in our CI with gcc8.

**Comment by sharkcz** [comment] 2019-02-14 19:43
With -O0 the tests pass, anything higher breaks it. The fun part begins again, hopefully I can localize the problematic part as last time :-)

**Comment by interwq** [comment] 2019-02-14 20:02
@sharkcz thanks for helping again! Let us know if anything needs to be fixed on our end.

**Comment by sharkcz** [comment] 2019-02-14 20:09
After a brief look I believe this is a mis-compilation of test/src/SFMT.c where the pseudo-random numbers are generated.

**Comment by sharkcz** [comment] 2019-02-15 10:48
reported https://bugzilla.redhat.com/show_bug.cgi?id=1677602 against gcc9 with a reduced test case

**Comment by sharkcz** [comment] 2019-02-18 15:48
and fixed in gcc trunk via https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89369

**Comment by sharkcz** [comment] 2019-02-18 15:50
I guess we can close this ticket.

**Comment by interwq** [comment] 2019-02-19 23:47
Thanks for help tracking down the issue @sharkcz !

**Closed by interwq** 2019-02-19 23:47 UTC
