### ISSUE TITLE
Alpine has dropped jemalloc due to no support.

### ISSUE THREAD

**Issue by shleeable** [jemalloc/jemalloc#1443] opened 2019-02-22 08:31 UTC
There are related issues with alpine and libjemalloc running ruby.

I'd like to start using jemalloc on my ruby docker containers but it seems to be missing some engagement with the community over there.

**Comment by davidtgoldblatt** [comment] 2019-02-22 18:37
I don't think there's much we can do here; the underlying issue is an incompatibility between jemalloc and the musl libc (that Alpine uses); musl would have to make a design decision to support replacing the allocator on its end. That would require extra work on musl's end, and it's not clear to me that the cost/benefit ratio is there for them; part of its pitch is its simplicity and lightweight design.

If you persuade them that they should support malloc replacement as a feature, I'm willing to help with bootstrapping issues on our end; but making this work isn't really just a question of writing code.

**Comment by ashleyhull-versent** [comment] 2019-02-23 14:53
Thanks for the additional detail.

**Comment by davidtgoldblatt** [comment] 2019-02-23 19:02
No problem! Closing this for now, but happy to take a new issue if something changes that makes this feasible.

**Comment by Kaisrlik** [comment] 2020-03-16 09:36
FYI: Recently, I wrote on musl mainling list and they confirm that musl supports usage of external malloc function[1].

[1]: https://www.openwall.com/lists/musl/2020/03/10/2

**Comment by davidtgoldblatt** [comment] 2020-03-16 15:48
OK, I'll add this to the queue. This is a very busy time for us, but I'll come back to it when I get a chance.

**Comment by thedanbob** [comment] 2020-05-05 15:59
For what it's worth, I was able to build jemalloc 5.2.1 on alpine 3.11 with no issues and ruby seems to use it just fine with `LD_PRELOAD`. I haven't tested it extensively yet, but I did run a memory stress test script I found [here](https://bugs.ruby-lang.org/issues/9113#note-12).

Sample Dockerfile:

```dockerfile
FROM ruby:2.7-alpine AS builder

RUN apk update && \
    apk add build-base

RUN wget -O - https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2 | tar -xj && \
    cd jemalloc-5.2.1 && \
    ./configure && \
    make && \
    make install

FROM ruby:2.7-alpine

COPY --from=builder /usr/local/lib/libjemalloc.so.2 /usr/local/lib/
ENV LD_PRELOAD=/usr/local/lib/libjemalloc.so.2
```

**Comment by killua99** [comment] 2020-05-08 14:12
The only thing, and that's because I'm not an expert I can't see ruby using jemalloc with @thedanbob docker build running `ruby -r rbconfig -e "puts RbConfig::CONFIG['MAINLIBS']"`

Perhaps I'm missing something else to make it work.

**Comment by thedanbob** [comment] 2020-05-08 14:23
Apparently, ruby can't see jemalloc (even though it's working) when you use `LD_PRELOAD`. According to [this comment](https://github.com/docker-library/ruby/issues/182#issuecomment-457616010) you can check it this way:

```bash
MALLOC_CONF=stats_print:true ruby -e "exit"
```

**Comment by booleanbetrayal** [comment] 2021-01-22 20:02
> Apparently, ruby can't see jemalloc (even though it's working) when you use `LD_PRELOAD`. According to [this comment](https://github.com/docker-library/ruby/issues/182#issuecomment-457616010) you can check it this way:
> 
> ```shell
> MALLOC_CONF=stats_print:true ruby -e "exit"
> ```

Can confirm and think that this issue could probably be closed (?)

**Comment by davidtgoldblatt** [comment] 2021-01-22 20:09
I believe that musl now supports malloc replacement, and my understanding is that jemalloc + musl now "just works". I was keeping this open until I had verified it myself, but I've seen enough people report it working that I figure it must be at least mostly OK.

Closing, but still happy to field reports of breakages if they arise.

**Closed by davidtgoldblatt** 2021-01-22 20:09 UTC
Labels: feature

**Comment by DirectorX** [comment] 2021-01-27 11:02
@thedanbob 
> 
> 
> Apparently, ruby can't see jemalloc (even though it's working) when you use `LD_PRELOAD`. According to [this comment](https://github.com/docker-library/ruby/issues/182#issuecomment-457616010) you can check it this way:
> 
> ```shell
> MALLOC_CONF=stats_print:true ruby -e "exit"
> ```

try to execute `ldconfig` to refresh the cache

**Comment by neohunter** [comment] 2021-05-02 20:50
On alpine 3.10 using docker image `ruby:2.5.5-alpine` i'm able to compile jemalloc, however when running

```
# set LD_PRELOAD=/usr/local/lib/libjemalloc.so.2
# ldconfig
# ruby -r rbconfig -e "puts RbConfig::CONFIG['MAINLIBS']"
# ruby -r rbconfig -e "puts RbConfig::CONFIG['LIBS']"
-lpthread -lgmp -ldl -lcrypt -lm 
# MALLOC_CONF=stats_print:true ruby -e "exit"
```

Any command the output is always empty (unless CONFIG['LIBS'].

I guess jemalloc is not loaded :(

**Comment by thedanbob** [comment] 2021-05-02 22:04
I tried the same and can confirm that trying to load jemalloc in `ruby:2.5.5-alpine` segfaults (even just `LD_PRELOAD=/usr/local/lib/libjemalloc.so.2 /bin/sh`). One workaround could be to build a ruby 2.5.5 image from alpine 3.11.

**Comment by neohunter** [comment] 2021-05-02 23:29
What I did for now is use this docker image instead:

```
FROM swipesense/ruby-jemalloc:2.5-stretch-slim
```

It has already ruby 2.5.7 compiled with jemalloc. 

It works like a charm, what I don't like however is taht is a much heavier image. But I just wanted to confirm if jamalloc offer me some performance improvement so it will work for now.

**Comment by srini38** [comment] 2021-06-05 02:52
Was trying to enable leak profiling using jemalloc on Alpine Linux 3.11.11, but it just hangs.  Without "--enable-debug --enable-prof" configure options to jemalloc, the command completes. Is this expected? Even tried Alpine 3.13.5 without any success. Any helpful pointers much appreciated.

```
/source/jemalloc-5.2.1 # cat /etc/alpine-release
3.11.11
/home/source/jemalloc-5.2.1 # ./configure --enable-debug --enable-prof && make -j10 && make install
/source/jemalloc-5.2.1 # MALLOC_CONF=prof_leak:true,lg_prof_sample:0,prof_final:true LD_PRELOAD=/usr/local/lib/libjemalloc.so.2 /bin/sh
^C
```

**Comment by BillyYarosh-WellSky** [comment] 2021-07-26 17:48
Wanted to follow up and ask if anyone has gotten jemalloc running on a baseimage without jemalloc precompiled into ruby? Based on this conversation, it doesn't sound like we have. I have tried [thedanbob's suggestion](https://github.com/jemalloc/jemalloc/issues/1443#issuecomment-624142451) and that doesn't work. I've also seen that solution provided elsewhere, and seems ruby doesn't recognize or acknowledge the LD_PRELOAD variable.

**Comment by chubbson** [comment] 2023-06-09 07:30
I think there is still no support of Jemalloc and Alpine. 
I also tried [thebandbob's suggestion](https://github.com/jemalloc/jemalloc/issues/1443#issuecomment-624142451) this will result in segmentation fault building the container. Also tried 5.3.0 of Jemalloc, with same error. I did not follow that rabbit hole in deep.

**Comment by lwmxiaobei** [comment] 2024-01-12 07:59
> I think there is still no support of Jemalloc and Alpine. I also tried [thebandbob's suggestion](https://github.com/jemalloc/jemalloc/issues/1443#issuecomment-624142451) this will result in segmentation fault building the container. Also tried 5.3.0 of Jemalloc, with same error. I did not follow that rabbit hole in deep.

I also think that apline and jemalloc are not supported. I tried to install jemalloc in docker. The installation was successful, but the smaps in /proc/pid did not have information about the jemalloc task. I tried many versions, but it didn't work, but debain is allowed

**Comment by Aubermean** [comment] 2024-01-17 13:33
There is support for Jemalloc in Alpine, at least on 3.18. Everything I read said it would be hard or near impossible but in reality it was as easy as this:

```
apt add --no-cache jemalloc
LD_PRELOAD=libjemalloc.so.2
MALLOC_CONF=stats_print:true ruby -e "exit"
```

Version 5 no less!

```___ Begin jemalloc statistics ___
Version: "5.3.0"

**Comment by thedanbob** [comment] 2024-01-17 14:10
Alpine restored support for jemalloc in 2022: https://gitlab.alpinelinux.org/alpine/aports/-/commit/e764db77406d02df1e6ee627daa808837c1a81ce

Edit: there's some useful info in this gist: https://gist.github.com/jjb/9ff0d3f622c8bbe904fe7a82e35152fc
 I can confirm that the method of patching ruby with jemalloc support, mentioned in the last comment there, works on Alpine:

```bash
apk add ruby jemalloc patchelf
patchelf --add-needed libjemalloc.so.2 /usr/bin/ruby
apk del patchelf
MALLOC_CONF=stats_print:true ruby -e "exit"
```

**Comment by lowzyyy** [comment] 2024-08-26 23:04
For alpine image:```

RUN apk add --no-cache jemalloc
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
```
