### ISSUE TITLE
Unused memory not purged (4.2.1 vs 5.2.1) in Telegram Desktop

### ISSUE THREAD

**Issue by nuclight** [jemalloc/jemalloc#2069] opened 2021-05-18 16:20 UTC
The Telegram Desktop folks were investigating why the messenger process leaks many Gigabytes on Linux when runnign for long. They found that there are no "real" leaks in terms of forgotten `free()` or whatever similar Valgrind would say (at least of significant size) but that there is problem with allocator which does not properly release memory back to system kernel. They found it by changing mmap threshold of glibc allocator and by using fresh mallocng from `musl` libc library (Alpint Linux, Void Linux).

They also tested jemalloc and said it leaks, too. But what I see on my FreeBSD 11 with jemalloc is that memory gets released back to system, not entirely, but I do not consider that as "leak".

Later experiments showed that jemalloc 4.2.1 on Linux does not leak and that FreeBSD -CURRENT with jemalloc 5.2.1 _do_ leak.

**Steps to reproduce:**

1) Install Telegram Desktop, login to Telegram
2) Open `top` ot `htop` or whatever you prefer; speedy Internet connection is recommended
3) Open channel https://t.me/tdesktop_crash and ensure settings for media play are as in last post
4) Observe `top` for `telegram-desktop` process' initial SIZE and RES
5) Scroll that channel as much as possible while watching `top` for `telegram-desktop` process' SIZE and RES
6) Close that channel (switch to another chat) and continue watching `top` for SIZE/RES

**Expected (ideal) behaviour:**

After reaching 1-4 Gb more, SIZE/RES of `telegram-desktop` drops to initial values at step 4.

**Acceptable behaviour:**

On jemalloc 4.2.1 with build options of FreeBSD 11.4, SIZE/RES shortly drop 1-2 Gb of peak size, then slowly decreases with time, initial values are not reached, though, being 100-200 Mb more.

**Actual behaviour (BUG):**

On jemalloc 5.2.1, be it on Linux with default options, or on FreeBSD 14-CURRENT, or Linux with build options of FreeBSD, memory consumption SIZE/RES **stays as high in peak and does not decrease with time**, being effectively **a leak** from user's perspective.

**Comment by interwq** [comment] 2021-06-23 00:12
jemalloc 5.x have a different page purging algorithm (time based decay, versus the ratio base previously). It sounds to me that somehow the time based decay isn't working well or triggered properly in this workload, resulting in the freed pages sitting around in the page cache. If you have the output from malloc_stats_print(), we'll be happy to take a look.

**Comment by nuclight** [comment] 2021-06-24 03:14
@interwq Could you please describe where to put this and/or compile options of jemalloc, if any should be different from defaults?

**Comment by interwq** [comment] 2021-06-28 21:10
@nuclight : of course. If it's possible / easy to change the application binary, you can insert `malloc_stats_print(NULL, NULL, NULL);` to the place you'd like stats output. Or spawn a new thread to output stats every few seconds.

If you don't want to change the binary, you can try the dev branch (listed in #2060) which contains a new feature to output stats periodically, e.g. adding `stats_interval:1000000` to MALLOC_CONF will print stats every these many bytes of allocations.

The stats when the issue happens (i.e. when you expect memory to be returned, then after another 10 seconds or so) will be most helpful.

**Comment by ilya-fedin** [comment] 2021-06-29 17:25
I specified `stats_interval:100000000` since `stats_interval:1000000` generates output of ~4 GB size. I can't figure out where the lines when the memory should been freed, so here's the output of all run time. It haven't output anything after 10 seconds (or at least I haven't seen that).
[jemalloc_stat.txt.zip](https://github.com/jemalloc/jemalloc/files/6735259/jemalloc_stat.txt.zip)

**Comment by nuclight** [comment] 2021-06-29 17:25
OK, I told this to @ilya-fedin who actively participates and experiments in Telegram Desktop. He said the stats is so big that it effectively hangs the process. He also tried imtermediate versions of `jemalloc` and said that 4.3.1 also frees memory but 4.4.0 is not. And "fix of huge-aligned allocation regression in 4.4.0" in 4.5  is not of help, 4.5 still not frees.

**Comment by ilya-fedin** [comment] 2021-06-29 17:27
> and said that 4.3.1 also frees memory but 4.4.0 is no

Yeah, 4.4.0 and 4.5.0 don't free the memory at all. 5.2.1 frees it slowly and not fully even after minutes

**Comment by interwq** [comment] 2021-06-29 22:25
The stats confirmed that the cached dirty pages built up, e.g. in the last snapshot, the dirty cache accounts for ~0.9G of RSS, while the application allocated is only ~0.2G.

As mentioned, one important change was the purging policy -- the new time-based decay tends to optimize for temporal reuse, e.g. with fast memory reuse cycles, the dirty cache stays around longer to help future allocations; while the previous ratio-based decay emphasizes on the cache size upper bound.

In our evaluation, the time-based approach performs better in most cases, although we are also aware that some pattern may cause issues: one major factor is the lack of activity, which caused the stall in the decay process (i.e. no malloc / free calls to trigger progress in time). If the application frees a bunch of memory and then suddenly stops invoking jemalloc (which is the pattern reported here), the dirty cache will get queued up and will have to wait until more activities to trigger purging. The solution we provide is the [background thread feature](https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md) -- this allows jemalloc to create its own threads, which will handle the decay operations even if the application threads go idle.

Please try it and see if it fixes the issue. We enable the option in our production set up as well. In the long term we still want to tweak the purging algorithm, to make it more resilient to access pattern changes; however having jemalloc owned threads likely still will be the best solution (and it may improve other metrics as well).

**Comment by ilya-fedin** [comment] 2021-06-29 22:34
Wow, it works wonderfully well with that option active, thanks a lot. It freed all the memory in multiple seconds back to initial value.

**Comment by ilya-fedin** [comment] 2021-06-29 22:46
I wonder what circular dependencies the man page talks about? :thinking:

**Comment by davidtgoldblatt** [comment] 2021-06-29 22:56
> I wonder what circular dependencies the man page talks about? 🤔

In some cases, the first call to malloc can be from within pthreads. If they do that while holding some lock that's *also* held during `pthread_create`, we'll deadlock. (Something similar can happen with the dynamic loader, too, so the most obvious fix of just creating the thread during a library constructor is not completely safe either).

**Comment by nuclight** [comment] 2021-06-29 23:39
So do you suggest `dirty_decay_ms:0` instead of background thread ? This option also helps.

**Comment by interwq** [comment] 2021-06-30 00:18
That will disable the dirty page cache completely. It usually will cause a non-trivial slowdown. Only use that if you want lowest memory usage, at the cost of extra syscalls and page faults etc.

We usually suggest enable the background thread feature, even w/o the idling issue. For example it often improves tail latency by offloading work from the application threads.

**Comment by interwq** [comment] 2021-06-30 00:18
Closing but feel free to ask anything

**Closed by interwq** 2021-06-30 00:18 UTC

**Comment by ilya-fedin** [comment] 2021-06-30 00:21
> It usually will cause a non-trivial slowdown.

A slowdown to glibc/musl point?

**Comment by interwq** [comment] 2021-06-30 00:28
Hard to estimate as it depends on the workload / pattern, e.g. some workload may be mostly fine as many requests can be satisfied by the thread cache; but "larger" workloads usually need to go down to the page allocator level often, which is where we cache the dirty pages.

Alternatively, you can try a non-zero but lower value for `dirty_decay_ms`, e.g. 1 second instead of the default 10 sec. This will allow caching but return to the OS sooner. Note that you also want to combine this with the background thread enabled.

**Comment by nuclight** [comment] 2021-06-30 11:33
> > I wonder what circular dependencies the man page talks about? thinking
> 
> In some cases, the first call to malloc can be from within pthreads. If they do that while holding some lock that's _also_ held during `pthread_create`, we'll deadlock. (Something similar can happen with the dynamic loader, too, so the most obvious fix of just creating the thread during a library constructor is not completely safe either).

Is it possible to enable background thread not in malloc.conf but later, to avoid this possible deadlock?

**Comment by davidtgoldblatt** [comment] 2021-06-30 15:15
Yep -- the background_thread mallctl setting is read/write; you can set it to `true` after startup (in main() or wherever, someplace you know is outside of pthreads internals), and it will start up background threads at that known safe point.

**Comment by ValZapod** [comment] 2022-06-25 21:34
Is this still broken? What allocator is used on windows, is it closed source?

**Comment by ilya-fedin** [comment] 2023-09-01 23:14
Is something broken in v5.3.0? I've noticed that the issue is back even with the background_thread option. If I replace background_thread with arenas.dirty_decay_ms = 0, the memory never gets released to the system. So none of the solutions seem to work now.

I also noticed that I can't change dss in runtime, I've tried like that:
```
#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)
...
		char dss[] = "disabled";
		mallctl("arena." STRINGIFY(MALLCTL_ARENAS_ALL) ".dss", nullptr, nullptr, &dss, sizeof(dss));
```
Launching with `MALLOC_CONF=stats_print:true` says `dss allocation precedence: "secondary"`. The documentation says it should work:
![](https://github.com/jemalloc/jemalloc/assets/17829319/f870d261-6d89-45ae-a41a-40bf8c126f70)
