### ISSUE TITLE
Dev branch # of CPU detection error when using CPU binding

### ISSUE THREAD

**Issue by tanghaodong25** [jemalloc/jemalloc#808] opened 2017-04-28 14:43 UTC
#### Test platform
ubuntu 16.10
gcc/g++ 6.2.0
numactl 2.0.11
jemalloc commit id: 5c56603e91d8d0021280615f86b95efe0463b6a8

#### Background
We're trying to run benchmark for ceph, a distributed objectstore, and hit some issues with jemalloc if using "numactl" to bind prcocess to specified numa node. After deep analysis, we suspected it was jemalloc problem. So we tried jemalloc "run_test.sh" with prefix "numactl --membind=0 --cpunodebind=0", it ran into error on ubuntu 16.10. We also tried ubuntu 14.04, there was no error.

#### Issue
```shell 
=== test/unit/bitmap ===
test_bitmap_initializer (non-reentrant): pass
test_bitmap_initializer (libc-reentrant): pass
test_bitmap_initializer (arena_new-reentrant): pass
test_bitmap_size (non-reentrant): pass
test_bitmap_size (libc-reentrant): pass
test_bitmap_size (arena_new-reentrant): pass
<jemalloc>: src/jemalloc.c:402: Failed assertion: "ind <= narenas_total_get()"
Aborted
Test harness error: test/unit/bitmap w/ MALLOC_CONF=""
Use prefix to debug, e.g. JEMALLOC_TEST_PREFIX="gdb --args" sh test/test.sh test/unit/bitmap
Makefile:439: recipe for target 'check_unit' failed
make: *** [check_unit] Error 1
test_alignment_and_size (non-reentrant): pass
test_alignment_and_size (libc-reentrant): pass
test_alignment_and_size (arena_new-reentrant): pass
--- pass: 9/9, skip: 0/9, fail: 0/9 ---

=== test/integration/allocated ===
<jemalloc>: src/jemalloc.c:402: Failed assertion: "ind <= narenas_total_get()"
Aborted
```
Thanks,
Haodong

**Comment by interwq** [comment] 2017-04-28 17:53
@tanghaodong25: yes we are aware of this issue. It's caused by # of CPUs not detected correctly when CPU binding is used (there was some dependency complication to detect it during bootstrapping). 

To workaround this issue for now, you can try one of the following when using binding:
1) add "percpu_arena:disabled" to your jemalloc config string, e.g. add 
const char* malloc_conf = "percpu_arena:disabled" in the source file.
2) manual set number of arenas, e.g. add "narenas:64" where 64 is the total # of cores in your system.

The two options may result in different performance characteristic. I suggest you try out both and see which one works better for you.

**Comment by interwq** [comment] 2017-04-28 17:55
Also, the commit you are using is from dev branch, which is still under development. If you want latest stable release, check here: https://github.com/jemalloc/jemalloc/releases

**Comment by tanghaodong25** [comment] 2017-04-29 04:22
Thanks @interwq for the quick reply. I'll try the config you suggested.

**Comment by tanghaodong25** [comment] 2017-05-02 04:07
@interwq both of the configuration you suggested work, and it performed better with "narenas:88" on my environment. Thanks.

**Comment by interwq** [comment] 2017-05-03 00:37
@tanghaodong25: You are welcome! If you don't mind, which config ended up better for your workload? You mentioned "narenas:88", is it alone or combined with "percpu_arena:disabled"? (assuming this is still on dev branch). We'll be tuning the defaults for the next release soon, so more data points are definitely welcomed.

**Comment by tanghaodong25** [comment] 2017-05-03 03:02
It is alone. "narenas:88" performed better, but a little(about ~2% performance better for 4K random workload), than "percpu_arena:disabled" on my 88 processors platform.

**Comment by interwq** [comment] 2020-01-06 21:47
Should be properly fixed by https://github.com/jemalloc/jemalloc/pull/1676.

**Closed by interwq** 2020-01-06 21:47 UTC
Labels: bug
