### ISSUE TITLE
Memory leak introduced between 5.01 and 5.1

### ISSUE THREAD

**Issue by mpghf** [jemalloc/jemalloc#1454] opened 2019-03-11 09:04 UTC
I've been experiencing a new memory leak that was introduced between 5.01 and 5.1 releases.  I've narrowed it down to a particular commit:  it starts on 3e64dae802b9f7cd4f860b0d29126cd727d5166b and affects all subsequent versions, including head revision.

The system is a fairly standard Gentoo Linux system:

4.9.72-gentoo-64Bit # 1 SMP PREEMPT Thu Aug 2 00:25:30 -00 2018 x86_64 Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz GenuineIntel GNU/Linux

The compiler is a standard gcc 5.4:

gcc (Gentoo 5.4.0-r4 p1.7, pie-0.6.5) 5.4.0

Prior to the commit above  (or using the stock Linux malloc), memory usage stays constant (~300 MB) indefinitely.  From that commit onward, memory usage grows quickly until the system runs out of memory (3.6 GB).

Running jemalloc with leak profiling enabled (as detailed on the wiki) shows no sign of the missing memory.

As for what I'm doing to provoke this:  

I've narrowed it down to a small piece of code, but the same code in a separate program doesn't provoke the same error, so I assume that it's the exact context that causes the problem.  The program in which this code is found is a medium size, proprietary application, with a number of threads (5 or so) running, although the other threads are doing less and allocating less memory.

The sample in questions looks like this (_**note that this code does not provoke the problem by itself**_):
```
#include <iostream>
#include <thread>
#include <list>
#include <chrono>

using namespace std;


class TestClass
{
public:
	TestClass(unsigned uLength)
	{
		p = new unsigned char[uLength];
		//The empty space is filled with useful data
		for(unsigned u = 0; u < std::min(uLength, 256u); u++) {
			p[u] = std::rand() | 0xff;
		}
	}
	~TestClass()
	{
		delete[] p;
	}
private:
	unsigned char *p = nullptr;
};

shared_ptr<TestClass> ExtractCaptures()
{
	shared_ptr<TestClass> p = make_shared<TestClass>(49340);
	return p;
}

int main()
{
	do {
		//It doesn't seem to matter whether this is a list or vector
		list<shared_ptr<TestClass>> captures;
		for(unsigned u = 0; u < 256; u++) {
			shared_ptr<TestClass> p = ExtractCaptures();
			//Removing the push_back below makes the problem disappear
			captures.push_back(p);
		}
		cout << "Length of captures: " << captures.size() << "\n";
	} while(1);
	return 0;
}
```

I'm happy to provide further input, apply patches, run with additional parameters, etc.

**Comment by interwq** [comment] 2019-03-11 16:16
Thanks for the detailed report @mpghf! I think I know what went wrong — it’s probably an unfortunate side effect of the max_active_fit feature when combined with a specific pattern of deallocating larger buffers. Before I put up the patch, can you please try running with ‘MALLOC_CONF=lg_extent_max_active_fit:63’. This should verify if I have the correct fix in mind.

**Comment by djwatson** [comment] 2019-03-11 17:56
Also likely fixed by #1448 ?

**Comment by interwq** [comment] 2019-03-11 20:11
@djwatson : I'm not totally convinced that we should remove max_active_fit yet. It was quite useful in reducing fragmentation for some patterns (in one of the long running binary we have); I agree it should be reevaluated if best_fit and delayed_coalesce are both gone, let's do more experiments there to make sure. It might still be useful for dirty extents.

**Comment by djwatson** [comment] 2019-03-11 20:35
@interwq  - The only use of max_active_fit is in best_fit - once best_fit is removed in #1448, it is irrelevant.

**Comment by interwq** [comment] 2019-03-11 20:48
@djwatson -- right now max_active_fit is tied to best_fit out of convenience, however it was intended to apply to dirty extents; if we get rid of  best_fit, we should still add it to dirty extents to see the effect of best fit; for the workload with the long running binary (`alloc(MBs); free(MBs); many alloc&free small` which splits the dirty large buffers into many pieces and eventually fragments VM space), I can still see the fit ratio been helpful.

**Comment by mpghf** [comment] 2019-03-12 06:11
@interwq Thanks for the quick response.  Setting MALLOC_CONF=lg_extent_max_active_fit:63 does indeed fix the problem.

**Comment by mpghf** [comment] 2019-03-12 06:41
@djwatson  @interwq 

I've tested #1448 too, and that also fixes the problem (without using the MALLOC_CONF options above).

**Comment by interwq** [comment] 2019-03-13 20:30
Thanks again for helping @mpghf. Much appreciated. We have a fix in the pipeline and should be out soon.

**Comment by interwq** [comment] 2019-03-15 06:28
Closing as the fix is landed in #1458

**Closed by interwq** 2019-03-15 06:28 UTC

**Comment by ObiWahn** [comment] 2019-03-21 13:52
Will there be a new jemalloc release?

**Comment by mpghf** [comment] 2019-03-22 06:24
@ObiWahn As I understand it, this should be in version 5.2, which should be released in a few weeks.
