### ISSUE TITLE
Multiple performance regressions since 3.6.0

### ISSUE THREAD

**Issue by glandium** [jemalloc/jemalloc#236] opened 2015-06-03 01:23 UTC
This is a followup to issue #230, but this time with data from Firefox.

See the graph on https://docs.google.com/spreadsheets/d/1XhBOUhaz_27SmqlrGEZDOnIEw4FSqB446BCT6LYX-PY/edit#gid=2009067671
(I wish this were less noisy)

Several things of note in there:
- performance has been stable between 3.0 and 3.6, then improved but degraded again.
- there are apparently roughly three regressions in there.
- the lowest number on that graph matches the value I get with mozjemalloc (not on the graph)
- the first regression is from 2c5cb61 + the config used during the tests (see below), which is kind of expected.
- another regression is 97c04a93838c4001688fe31bf018972b4696efe2
- another regression would seem to be 8a03cf039cd06f9fa6972711195055d865673966

Note that it's only one particular test, and we've seen regressions across the board. Hopefully, they are all correlated. I'm going to check that commit that got the best score and see how it does across all our tests.

Steps to reproduce the benchmark:
- download a firefox nightly from `https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/`
- `hg clone http://hg.mozilla.org/build/talos` or `git clone https://github.com/mozilla/build-talos`
- in that clone, run `python INSTALL.py` (requires virtualenv and setuptools)
- then `. bin/activate`
- Build jemalloc with: `autogen.sh --disable-valgrind --enable-stats --enable-fill --with-jemalloc-prefix=je_ ac_cv_func_memalign=yes ac_cv_func_valloc=yes -with-mangling=malloc_usable_size:replace_malloc_usable_size,valloc:replace_valloc,memalign:replace_memalign,free:replace_free,realloc:replace_realloc,calloc:replace_calloc,aligned_alloc:replace_aligned_alloc,posix_memalign:replace_posix_memalign,malloc:replace_malloc`
- Run the test with `JE_MALLOC_CONF=narenas:1,lg_chunk:20,tcache:false,junk:free LD_PRELOAD=path/to/libjemalloc.so talos --develop -e path/to/firefox --activeTests sessionrestore_no_auto_restore --cycles 10`
- It will output a `local.json` file that you can pass to the following python script to get a single value:

```python
import json
import sys

def geomean(nums):
    return reduce(lambda x, y: x * y, nums) ** (1.0 / len(nums))

file = sys.argv[1]
with open(file) as fd:
    data = json.load(fd)
print geomean(data[0]['results']['sessionrestore_no_auto_restore'][1:])
```

A few notes on the `JE_MALLOC_CONF` used:
- it is equivalent to our config for mozjemalloc: 1 arena, no tcache, 1MB chunks, poisoning of free()ed memory.
- I haven't tested what the recent drop of chunk size did, I will run tests again with lg_chunk removed.
- Firefox uses many threads, and the memory overhead of tcache as a consequence is not reasonable that we would be willing to turn it on. Arena cache (issue #148) seems like it would work better for us. Alternatively, we could try tcache + regular flushes.
- ISTR increasing the number of arenas did help performance (only very slightly), with no noticeable memory overhead. I'll check again.

**Comment by glandium** [comment] 2015-06-03 01:58
> another regression would seem to be 8a03cf0 

I added data for jemalloc builds with --disable-cache-oblivious (red on the graph)... and the results were not significantly different.

**Comment by glandium** [comment] 2015-06-03 03:01
> I haven't tested what the recent drop of chunk size did, I will run tests again with lg_chunk removed.

Added in orange. It would seem 256KB chunks were better than 1MB chunks... until 8a03cf0.

**Comment by glandium** [comment] 2015-06-03 03:12
> Note that it's only one particular test, and we've seen regressions across the board. Hopefully, they are all correlated. I'm going to check that commit that got the best score and see how it does across all our tests.

So, I ran that commit (f1cf3ea4753260d37c9a43463bae2140e00e16f0) on all our tests, and here are the results:
- against mozjemalloc (old is mozjemalloc, new is jemalloc3)
https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=8696e20bf464&newProject=try&newRevision=27dcc008d8bf
- against jemalloc commit 836bbe9951a903b2d76af53dfb3ad53ad186f8b9 (old is that commit, new is f1cf3ea4753260d37c9a43463bae2140e00e16f0):
https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=503bdff5322e&newProject=try&newRevision=27dcc008d8bf

Note that those builds also use `lg_dirty_mult:6`, which I happen to have forgotten in `JE_MALLOC_CONF` during my local tests. They also use the default jemalloc chunk size, so 256KB for 836bbe9951a903b2d76af53dfb3ad53ad186f8b9 and 4MB for f1cf3ea4753260d37c9a43463bae2140e00e16f0. I'm going to push another attempt with 1MB chunk and free poisoning (so, using 2c5cb613dfbdf58f88152321b63e60c58cd23972 instead of f1cf3ea4753260d37c9a43463bae2140e00e16f0)

**Comment by glandium** [comment] 2015-06-03 06:27
- f1cf3ea+4MB chunks (old) vs. 2c5cb61+1MB chunks (new):
https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=27dcc008d8bf&newProject=try&newRevision=7d69966ea06d
- mozjemalloc (old) vs. 2c5cb61+1MB chunks (new):
 https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=8696e20bf464&newProject=try&newRevision=7d69966ea06d
Note the latter is actually the regressions I was already after a few months back.

**Comment by jasone** [comment] 2015-06-26 04:10
I've spent the past two days looking at this, and unfortunately I can't conclude much, because the incidental performance variation between very similar revisions hides whatever effects there may be.  I generated a vaguely similar [plot](https://docs.google.com/spreadsheets/d/1klowKhPk-WsKkW3YXxjVs54RWqxKOijFkh6SDcMFHFg/edit?usp=sharing) using similar methodology (arithmetic mean rather than geometric mean, no junk filling), but noise is bad enough that it's hard to tell with more fidelity than 10 revisions where a performance change actually occurred.  I tested a bunch of different combinations of reversions and hacks, but the only one I'm confident is a regression here is 8a03cf039cd06f9fa6972711195055d865673966.

The benchmark does very little allocation (~0.5M requests), and even extreme changes to jemalloc have questionable effect (e.g. disabling all purging, disabling run quantizing and/or first fit search, octupling small run capacities, etc.).  Is there some other benchmark we can look at to get cleaner results?  We need something that really strains jemalloc, and whatever we use needs to run much longer so that startup/shutdown noise is inconsequential.

**Comment by jasone** [comment] 2015-07-06 22:49
Any ideas, @glandium?  If all goes well the 4.0.0 release will be ready to go in about a week, and I'd like to understand this issue beforehand if possible.

**Comment by glandium** [comment] 2015-07-07 05:09
Sorry for the late answer. You can try to use one of the following instead of sessionrestore_no_auto_restore:
- tart
- ts_paint
- a11yr
- sessionrestore
- tresize

and maybe a few of the others you can find with `grep -A1 register_test talos/test.py`

You'll need to adjust the python snippet reading local.json.

Those tests are, indeed, generally noisy, but we can't dismiss the regressing trend because of that. :(

**Comment by glandium** [comment] 2015-07-07 05:15
> The benchmark does very little allocation (~0.5M requests)

It should be noted that having "so little" allocations affect Firefox startup performance so notably is worrying.

**Comment by jasone** [comment] 2015-07-07 17:19
On the contrary, there is little enough allocation work being done that we don't know to what degree the regression is due to libjemalloc.so size/layout changes that impact process initialization.  The library size has increased by nearly 30% since 3.6.0 (with default options), so this is almost certainly at least part of the explanation.

I have extensively benchmarked recent dev versions of jemalloc in various other contexts, especially HHVM handling production Facebook traffic, and the results are unequivocally quite positive.  However, an awful lot has changed in jemalloc, and the combination of intended/ancillary effects can (and do!) obscure regressions.  I worry about what's slipping through testing, which is why I take reports such as yours very seriously, @glandium.  On top of that, you've built up oodles of good karma with all your contributions, and I'm willing to go the extra mile on this as a result.  The problem is, I can't glean any actionable data.  My hope is that if there's really a serious regression in jemalloc, you/Mozilla have other benchmarks in place that can show clearly what changes are to blame.  On the flip side, is it possible that these short-lifetime benchmark changes don't indicate any actual impact on user experience?

**Comment by glandium** [comment] 2015-07-07 21:26
sessionrestore*, tpaint, tresize and ts_paint are essentially benchmarks of Firefox startup. Tart is a tab animation test. Regressions on thoses tests indicate actual impact on user experience.

**Comment by jasone** [comment] 2015-07-08 03:09
Cool, I will experiment with those soon and see what turns up.

**Comment by jasone** [comment] 2015-07-17 19:37
During a similar performance regression investigation based on [Pyston](https://github.com/dropbox/pyston), I determined that first-fit run allocation was a substantial regression under a wide variety of scenarios, and reverted it (aa2826621e1793db9faea31e803690ccbe36f14c).

Chunk size also matters, but mainly because of transparent huge pages, so I changed the chunk size to 2 MiB (5bd879646cdb303045096fc2b9d75f565313afa8).  Unfortunately, this doesn't even come close to solving the problematic interactions with transparent huge pages.  As physical memory fragments, the kernel has to work harder to create contiguous available memory for huge pages, and at some point, this starts failing and the kernel never returns to a state in which huge pages are readily available.  I repeatedly reached this state in under a day each time with an Ubuntu 15.04 (3.19.0-22-generic) system while intermittently running various benchmarks.

While running the ```tart``` benchmark I noticed that the ```reruns``` jemalloc statistic is extremely high.  This means that small allocation/deallocation requests are often paying the high cost of red-black tree operations (see ```arena_bin_lower_run()```).  I've continued to maintain that statistic since early jemalloc versions because if it were high, then performance would almost certainly be suffering.  However, this is the first time I recall seeing this scenario actually play out.  I fixed a bug (e7a1058aaa6b2cbdd19da297bf2250f86dcdac89) three years ago that had the potential to increase ```reruns```, and I'm guessing the Mozilla version of jemalloc has this bug, but haven't checked.

I'm still struggling with whether to revert 8a03cf039cd06f9fa6972711195055d865673966 (Implement cache index randomization for large allocations.).  For some workloads it has a huge positive impact, but it clearly adds both memory and computation overhead.  In the case of ```sessionrestore_no_auto_restore```, large allocations make up roughly 1% of all allocations, which is enough for the overhead to be consistently measurable.  My general bias is toward algorithms that limit worst-case behavior, even at the expense of the common case, within reason.  Most applications won't suffer from slower large allocation because the large allocation rate is relatively much smaller than 1%.  However, the potential magnitude of the overhead is troubling to a degree that I've poked around looking for outright bugs.  As near as I can tell, the code is working as intended, but the combination of using extra pages (minor effect) and increased run fragmentation due to run sizes having few common divisors (major effect?) makes me doubt the overall utility of the feature.

**Comment by jasone** [comment] 2015-07-17 20:45
I added issue #243 to track transparent huge page interaction issues.  Meanwhile, the only way to achieve repeatable benchmarks is to disable automatic transparent huge pages (e.g. ```echo madvise >/sys/kernel/mm/transparent_hugepage/enabled```) or to reboot often.

**Comment by jasone** [comment] 2015-07-17 23:43
I added the ```config.cache_oblivious``` mallctl in f2bc85298c1cd6f4e95fbbeeb7ccc32ff52a1d8f, with the intention of leaving the option enabled by default for the 4.0.0 release.  @glandium, you will almost certainly want to build Firefox with ```--disable-cache-oblivious```, and with that, I think all the regressions associated with this issue are resolved.

**Comment by glandium** [comment] 2015-07-18 00:49
I will check this next week. Please note, though, that --disable-cache-oblivious made no difference when I tried (mentioned in https://github.com/jemalloc/jemalloc/issues/236#issuecomment-108159376 ). I haven't looked in detail, but maybe --disable-cache-oblivious doesn't actually restore the old code.

**Comment by glandium** [comment] 2015-07-28 08:47
So, it would seem as of 218b15c, with --disable-cache-oblivious, we're back to the level of b4acf73. So that means the regressions since 3.6 seem to be gone, but there is still the good old difference with mozjemalloc. I'll come back with more testing on other platforms than Linux, now that OSX and Windows builds are fixed or close to be fixed.

**Comment by jasone** [comment] 2015-08-07 08:11
Assuming I didn't introduce any regressions with the recent chunk hook work, the 4.0.0 release should happen within a few days.  Please let me know if there's anything else to consider in this issue.

**Comment by glandium** [comment] 2015-08-07 08:20
Sorry, I was busy with other things. So, compared to the jemalloc 3.something commit we had in our tree, this doesn't seem to be regressing, which is a good thing. There are still significant regressions when comparing with mozjemalloc. See https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=ecd9322a6e79&newProject=try&newRevision=fa358692aeaf
(ignore kraken, tcanvasmark, v8_7, and dromaeo*)

**Comment by jasone** [comment] 2015-08-09 17:46
Cool, I'm going to close this issue.  Hopefully we will eventually figure out where the difference in mozjemalloc lies, but it's not blocking the 4.0.0 release.

**Closed by jasone** 2015-08-09 17:46 UTC

**Comment by thestinger** [comment] 2015-08-09 17:49
I have a feeling it's just caused by the fine-grained locking. #14 would help because it would eliminate most of the benefits from that (would still help for data in different bin sizes being sent between threads), although at the expense of less data locality due to threads migrating around.

**Comment by glandium** [comment] 2015-08-11 22:29
> I have a feeling it's just caused by the fine-grained locking

I tried comparing after removing per-bin lock, and it made no significant difference.

**Comment by glandium** [comment] 2015-08-11 22:41
err, in fact, removing per-bin lock does clearly regress on one particular test.
