### ISSUE TITLE
Warnings Compiling on Debian 11

### ISSUE THREAD

**Issue by shpml** [jemalloc/jemalloc#2130] opened 2021-09-23 06:40 UTC
I have run into some warnings when compiling on debian 11 which weren't there on debian 10.

Steps to reproduce
```
docker run -it debian:stable-slim bash
root@64e1da2c49a7:/# apt-get update -qq && apt-get install build-essential curl -qq -y &&\
    curl -sL https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2 | tar -xj --no-same-owner &&\
    cd jemalloc-5.2.1 &&\
    ./configure > /dev/null && make -j 
```

Debian and gcc version info:
```
root@64e1da2c49a7:/jemalloc-5.2.1# gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@64e1da2c49a7:/jemalloc-5.2.1# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@64e1da2c49a7:/jemalloc-5.2.1#
```

Error Message Sample:
```
gcc -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -pipe -g3 -fvisibility=hidden -O3 -funroll-loops -fPIC -DPIC -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/sc.sym.o src/sc.c
src/jemalloc.c:2986:7: warning: '__libc_calloc' specifies less restrictive attributes than its target 'calloc': 'alloc_size', 'leaf', 'malloc', 'nothrow' [-Wmissing-attributes]
 2986 | void *__libc_calloc(size_t n, size_t size) PREALIAS(je_calloc);
      |       ^~~~~~~~~~~~~
gcc -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -pipe -g3 -fvisibility=hidden -O3 -funroll-loops -fPIC -DPIC -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/sz.sym.o src/sz.c
In file included from include/jemalloc/internal/jemalloc_internal_decls.h:63,
                 from include/jemalloc/internal/jemalloc_preamble.h:5,
                 from src/jemalloc.c:2:
/usr/include/stdlib.h:542:14: note: '__libc_calloc' target declared here
  542 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^~~~~~
src/jemalloc.c:3001:7: warning: '__libc_valloc' specifies less restrictive attributes than its target 'valloc': 'alloc_size', 'leaf', 'malloc', 'nothrow' [-Wmissing-attributes]
 3001 | void *__libc_valloc(size_t size) PREALIAS(je_valloc);
      |       ^~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_internal_decls.h:63,
                 from include/jemalloc/internal/jemalloc_preamble.h:5,
                 from src/jemalloc.c:2:
/usr/include/stdlib.h:574:14: note: '__libc_valloc' target declared here
  574 | extern void *valloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~
src/jemalloc.c:2998:7: warning: '__libc_realloc' specifies less restrictive attributes than its target 'realloc': 'alloc_size', 'leaf', 'nothrow' [-Wmissing-attributes]
 2998 | void *__libc_realloc(void* ptr, size_t size) PREALIAS(je_realloc);
      |       ^~~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_internal_decls.h:63,
                 from include/jemalloc/internal/jemalloc_preamble.h:5,
                 from src/jemalloc.c:2:
/usr/include/stdlib.h:550:14: note: '__libc_realloc' target declared here
  550 | extern void *realloc (void *__ptr, size_t __size)
      |              ^~~~~~~
src/jemalloc.c:2995:7: warning: '__libc_memalign' specifies less restrictive attributes than its target 'memalign': 'malloc', 'nothrow' [-Wmissing-attributes]
 2995 | void *__libc_memalign(size_t align, size_t s) PREALIAS(je_memalign);
      |       ^~~~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_preamble.h:21,
                 from src/jemalloc.c:2:
include/jemalloc/internal/../jemalloc.h:83:23: note: '__libc_memalign' target declared here
   83 | #  define je_memalign memalign
      |                       ^~~~~~~~
src/jemalloc.c:2885:1: note: in expansion of macro 'je_memalign'
 2885 | je_memalign(size_t alignment, size_t size) {
      | ^~~~~~~~~~~
src/jemalloc.c:2992:7: warning: '__libc_malloc' specifies less restrictive attributes than its target 'malloc': 'alloc_size', 'leaf', 'malloc', 'nothrow' [-Wmissing-attributes]
 2992 | void *__libc_malloc(size_t size) PREALIAS(je_malloc);
      |       ^~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_internal_decls.h:63,
                 from include/jemalloc/internal/jemalloc_preamble.h:5,
                 from src/jemalloc.c:2:
/usr/include/stdlib.h:539:14: note: '__libc_malloc' target declared here
  539 | extern void *malloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~
src/jemalloc.c:2989:6: warning: '__libc_free' specifies less restrictive attributes than its target 'free': 'leaf', 'nothrow' [-Wmissing-attributes]
 2989 | void __libc_free(void* ptr) PREALIAS(je_free);
      |      ^~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_internal_decls.h:63,
                 from include/jemalloc/internal/jemalloc_preamble.h:5,
                 from src/jemalloc.c:2:
/usr/include/stdlib.h:565:13: note: '__libc_free' target declared here
  565 | extern void free (void *__ptr) __THROW;
      |             ^~~~
gcc -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -pipe -g3 -fvisibility=hidden -O3 -funroll-loops -fPIC -DPIC -c -D_GNU_SOURCE -D_REENTRANT -Iinclude -Iinclude -DJEMALLOC_NO_PRIVATE_NAMESPACE -o src/tcache.sym.o src/tcache.c
gcc -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero
```

**Comment by Lapenkov** [comment] 2021-09-23 21:06
These warnings started to appear since `gcc-9`. Debian 10 uses `gcc-8` by default, hence you didn't see these warnings before. The issue has been fixed since `5.2.1`, if you build from `dev`, you won't see the warnings.

Closing, as the issue is a duplicate of https://github.com/jemalloc/jemalloc/issues/1612

**Closed by Lapenkov** 2021-09-23 21:06 UTC
