### ISSUE TITLE
Degraded performance in rallocx-heavy workloads from 4.x to 5.2.x

### ISSUE THREAD

**Issue by wesm** [jemalloc/jemalloc#1621] opened 2019-09-05 16:56 UTC
hi, earlier this year we upgraded to jemalloc 5.2.0 and in investigating some performance issues (see [some analysis](https://issues.apache.org/jira/browse/ARROW-6417?focusedCommentId=16923607&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16923607)) found that jemalloc 5.2.0 performs a lot differently in workloads involving `rallocx`.

The last version of the project we were using was 17c897976c60b0e6e4f4a365c751027244dada7a, which included some patches we needed

This is how we configure the project in our CMake setup

```
    CONFIGURE_COMMAND ./configure
                      "AR=${CMAKE_AR}"
                      "CC=${CMAKE_C_COMPILER}"
                      "--prefix=${JEMALLOC_PREFIX}"
                      "--with-jemalloc-prefix=je_arrow_"
                      "--with-private-namespace=je_arrow_private_"
                      "--without-export"
                      # Don't override operator new()
                      "--disable-cxx" "--disable-libdl"
                      # See https://github.com/jemalloc/jemalloc/issues/1237
                      "--disable-initial-exec-tls" ${EP_LOG_OPTIONS}
```

previously it was configured like this:

```
CONFIGURE_COMMAND ./autogen.sh "AR=${CMAKE_AR}" "CC=${CMAKE_C_COMPILER}" 
"--prefix=${JEMALLOC_PREFIX}" 
"--with-jemalloc-prefix=je_arrow_" 
"--with-private-namespace=je_arrow_private_" 
"--disable-tls"
```

I am happy to do some analysis with perf or make the issue easier to reproduce, let me know if you have any advice or ideas

**Comment by davidtgoldblatt** [comment] 2019-09-05 17:52
Probably the easiest thing to start with would be some perf output of the call graph starting at rallocx. One possibility that jumps to mind might be an interaction with the oversize_threshold option, which has been added in the interim; playing around with the values there might confirm/reject that guess.

**Comment by interwq** [comment] 2019-09-05 18:07
Like David mentioned, running 5.2 with env var `MALLOC_CONF=oversize_threshold:0` will tell if it's related to the new feature we added there. Otherwise, if you can share the rallocx call graph, and the output from `malloc_stats_print(NULL, NULL, NULL)` that would be very helpful.

**Comment by wesm** [comment] 2019-09-05 21:34
Thanks, I'll do this when I can find some time (I've already been chasing my tail on this for a good day or so), we are in the midst of a release push and I found the performance issue during some routine benchmarking.

**Comment by pitrou** [comment] 2019-09-09 14:31
Ok, I ran some of our benchmarks here (Ryzen 7 1700 with gcc 7.4.0 on Ubuntu 18.04):
* with jemalloc 4.5.0-3-g17c89797:
```
BufferBuilderTinyWrites/real_time    280646656 ns    280448005 ns            7 bytes_per_second=912.179M/s
BufferBuilderSmallWrites/real_time    47562592 ns     47521756 ns           44 bytes_per_second=5.25623G/s
BufferBuilderLargeWrites/real_time    22999670 ns     22983857 ns           91 bytes_per_second=10.8116G/s
BuildBooleanArrayNoNulls              40715625 ns     40682794 ns           52 bytes_per_second=6.1451G/s
BuildIntArrayNoNulls                  38439107 ns     38406246 ns           55 bytes_per_second=6.50936G/s
BuildAdaptiveIntNoNulls               22238250 ns     22218390 ns           94 bytes_per_second=11.2519G/s
```
* with jemalloc 5.2.0:
```
BufferBuilderTinyWrites/real_time    325650523 ns    325242598 ns            5 bytes_per_second=786.119M/s
BufferBuilderSmallWrites/real_time    84839138 ns     84600550 ns           25 bytes_per_second=2.94675G/s
BufferBuilderLargeWrites/real_time    82205177 ns     81906001 ns           25 bytes_per_second=3.02491G/s
BuildBooleanArrayNoNulls              63837462 ns     63665441 ns           33 bytes_per_second=3.92678G/s
BuildIntArrayNoNulls                  83751676 ns     83575870 ns           25 bytes_per_second=2.99129G/s
BuildAdaptiveIntNoNulls               32953753 ns     32868157 ns           64 bytes_per_second=7.60615G/s
```
* with jemalloc 5.2.0 + `JE_ARROW_MALLOC_CONF=oversize_threshold:0`:
```
BufferBuilderTinyWrites/real_time    284035665 ns    283880333 ns            7 bytes_per_second=901.295M/s
BufferBuilderSmallWrites/real_time    69108060 ns     69049810 ns           30 bytes_per_second=3.61752G/s
BufferBuilderLargeWrites/real_time    39222508 ns     39197293 ns           51 bytes_per_second=6.33981G/s
BuildBooleanArrayNoNulls              37331954 ns     37303579 ns           57 bytes_per_second=6.70177G/s
BuildIntArrayNoNulls                  22160434 ns     22146805 ns           74 bytes_per_second=11.2883G/s
BuildAdaptiveIntNoNulls               16852999 ns     16841447 ns          118 bytes_per_second=14.8443G/s
```
(note that, in the last configuration, `BuildIntArrayNoNulls` is very variable and oscillates between 6 GB/s and 23 GB/s...)

So the `oversize_threshold` setting manages to offset some of the performance difference, though the performance profile seems different as well.

**Comment by interwq** [comment] 2019-09-09 18:34
Thanks for sharing the results @pitrou. The `oversize_threshold` feature uses a dedicated arena for requests beyond the threshold (default is 8M); in our production tests this improves VM fragmentation quite a bit and reduces overall RSS. I'd guess the memory usage with the benchmark is lowered with the feature enabled as well.

Based on the numbers shown, I'm guessing the benchmark is more on the tight loop side, where we may not do very meaningful computation with the entire allocated buffer? If that's the case, I wouldn't worry much about the specific benchmark vs jemalloc 4.x. One observation motivated the feature was, in practice the large buffers won't get allocated super frequently and tend to stay longer, and separating them into a different arena avoids fragmentation and reduces RSS. In other words, for these huge allocations we expect filling the buffer and processing the data to be the dominating cost, while the allocation path should focus on minimizing fragmentation.

If you have `perf record` output and annotate / callgraph of realloc, I'll be happy to take a look.

**Comment by pitrou** [comment] 2019-09-09 18:36
What does `oversize_threshold:0` do? Does it enable the feature always or disable it always?

**Comment by interwq** [comment] 2019-09-09 18:38
> What does oversize_threshold:0 do?

It disables the feature all the way. http://jemalloc.net/jemalloc.3.html#opt.oversize_threshold

**Comment by pitrou** [comment] 2019-09-09 18:41
I see. The benchmarks build up an array progressively by appending data and upsizing where necessary (there's an overallocation scheme). So it's light on actual computation. But the arrays are rather large (several hundreds of megabytes), so if reallocation has to copy memory performance suffers a lot.

**Comment by pitrou** [comment] 2019-09-09 18:43
Oh, and I'll do a `perf` run when I find the time.

**Comment by interwq** [comment] 2019-09-09 18:47
> so if reallocation has to copy memory performance suffers a lot

My guess is the amount of copying doesn't change much (hopefully `perf` can verify this); the measured difference should be mainly from the dedicated arena, either from contention (if many threads are tight looping) or eagerly purging the freed large buffers.

**Comment by pitrou** [comment] 2019-09-09 19:06
With jemalloc 5.2.0 and `oversize_threshold` enabled, `perf` tells me 43% of the time is spent in page faults. With `oversize_threshold` disabled, only 1% of the time is spent in page faults. This seems to be the main difference between both 5.2.0 profiles.

**Comment by pitrou** [comment] 2019-09-09 19:34
Other surprising result: `oversize_threshold:4096` gives similar results as `oversize_threshold:0` (i.e. much better than default).

**Comment by interwq** [comment] 2019-09-09 21:16
re: >40% time spent in page faults in the benchmark -- this confirms again that the oversize_threshold feature is to "blame" here. That's the part `eagerly purging the freed large buffers` I mentioned above. The allocations beyond the specified threshold get purged immediately instead of going through the normal decay pipeline, mainly to reduce RSS / fragmentation. We do consider this to be the desired behavior in practice.

To sum up, I won't consider the difference in this specific benchmark results a regression. However please do let us know if your workload does reach the point where the default threshold hurts. With the production workload we tested, in the worst case this could be a tiny CPU increase but saves sizable RSS.

re: threshold set to 4k is identical to 0, values not within large size classes disables this feature. The larger the value, the closer the behavior is to no this feature.

**Comment by wesm** [comment] 2019-09-09 21:27
The benchmark we are focused on here is representative of some of our key workloads, which revolve around reading binary data files and materializing those in memory. We don't always know up front until the files have been decoded how much space they'll take up, so we use a `std::vector`-like quadratic allocation strategy to expand the built buffers as data is appended. In some workloads we do a chunking strategy to avoid large allocations, but it is not always possible. 

FWIW, A lot of data analytics systems will have workloads that look like this. 

@pitrou can we set this value at compile time? Setting an environment variable won't be practical in production

**Comment by interwq** [comment] 2019-09-09 21:39
re: revolve around reading binary data files and materializing those in memory

This should be all fine. However I'm guessing in the benchmark the buffers get threw away almost immediately with little work done on them? That would cause the overhead observed here; in our experience the processing time of the huge buffers naturally rate limit the operation rate.

The value can be set at compile time, e.g. by adding `const char* malloc_conf = "oversize_threshold:0"`; I'd still suggest trying w/o it and see if it's a measurable CPU / memory change.

**Comment by pitrou** [comment] 2019-09-10 09:03
> However I'm guessing in the benchmark the buffers get threw away almost immediately with little work done on them?

Right, this is the case. Still, this is a bit bothersome: we would like to be able to benchmark the performance of our array building routines (including whether they cooperate nicely with the memory allocator, which is important given that Arrow is meant for large or huge datasets). The costs you're talking about would still exist in a "normal" scenario, right? Do you imply they would be hidden by other costs? Something else?

**Comment by pitrou** [comment] 2019-09-10 09:15
Now, here's an interesting datapoint: jemalloc 5.2.0 is ~20% _faster_ than 4.5.0 on a benchmark of reading a CSV file from Python, using multiple threads (on a CSV file of integer columns: 1.5 GB/s with 5.2.0, 1.25 GB/s with 4.5.0). But that benchmark is not reallocating (and `oversize_threshold:0` doesn't make a difference).

**Comment by interwq** [comment] 2019-09-17 22:47
> we would like to be able to benchmark the performance of our array building routine

This shouldn't prevent that. What I'm saying is, the results with oversize_threshold and w/o are not easily comparable. With oversize_threshold the huge buffers get purged immediately instead of being cached / hogged by one arena, which helps RSS and fragmentation -- w/o this feature, a 1G buffer freed by one thread may stick around for seconds and can't be reused by other arenas / threads; further more, when reused within the same arena, the huge buffer tends to be split into smaller and smaller pieces which results in VM fragmentation eventually.

The cost of eagerly purging the huge buffer is amplified in the benchmark, coming from the very high rate of ditching > 8M buffers. In reality the rate won't be so high and the cost will be much lower; it's also compensated by the improved locality -- we observe multiple % of jemalloc metadata usage reduction, which helps locality (e.g. LLC and TLB) on the common path.

I'd consider the regression mentioned as a false-positive. You can test w/ `oversize_threshold:0`  if you'd like to stress the large deallocation path w/o the purging activity; IMO keep it is fine and it's still a useful benchmark for detecting issues.

**Comment by wesm** [comment] 2019-09-17 22:58
I would say that the "allocate and quickly dispose" pattern is somewhat characteristic of analytic workloads. We'll keep this in mind in our benchmarking, and I think it would be good as we have more complex applications to add and remove the `oversize_threshold` override to see what the impact on the net application efficiency is

**Comment by interwq** [comment] 2019-09-17 23:36
My best guess is the "allocate and quickly dispose" pattern should be fine, as the computation in between will make it not as frequent as in a stress benchmark.

Closing but feel free to let us know if anything.

**Closed by interwq** 2019-09-17 23:36 UTC

**Comment by wesm** [comment] 2019-09-18 00:06
Thanks for your assistance. We've upgraded the project back to jemalloc 5.2.1 with some conf tweaks for the time being
