### ISSUE TITLE
os_overcommits_proc does not close open fd

### ISSUE THREAD

**Issue by cferris1000** [jemalloc/jemalloc#418] opened 2016-06-30 16:33 UTC
The function os_overcommits_proc opens /proc/sys/vm/overcommit_memory, but doesn't close the fd.

This means that every call will leak a file decsriptor.

**Comment by djwatson** [comment] 2016-06-30 16:43
dupe of #399

**Comment by jasone** [comment] 2016-07-07 19:54
Tracking in #399.

**Closed by jasone** 2016-07-07 19:54 UTC
